<?php
session_start();
require_once 'koneksi.php';
require_once 'includes/auth.php';
require_once 'includes/spp_billing.php';
requireRole(['admin']);
if (!spp_billing_schema_ready($koneksi)) die('Schema Master SPP belum tersedia. Jalankan sql/add_spp_billing_and_deposit.sql.');
if (empty($_SESSION['csrf_master_spp'])) $_SESSION['csrf_master_spp']=bin2hex(random_bytes(32));

function mspp_e($value): string { return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8'); }
function mspp_money($value): string { return number_format((float)$value,0,',','.'); }
function mspp_amount($value): float { return (float)str_replace(['.',','],['','.'],trim((string)$value)); }
function mspp_redirect(string $year): void { header('Location: master_spp.php?tahun='.urlencode($year));exit; }

$selectedYear=trim((string)($_GET['tahun']??$_POST['tahun_ajaran']??du_current_academic_year()));
try{$selectedYear=du_normalize_academic_year($selectedYear);}catch(Throwable $e){$selectedYear=du_current_academic_year();}
$master=spp_master_ensure_year($koneksi,$selectedYear);$masterId=(int)$master['id'];
$flash=$_SESSION['flash']??null;unset($_SESSION['flash']);

if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        if(!hash_equals($_SESSION['csrf_master_spp'],(string)($_POST['csrf_token']??'')))throw new RuntimeException('Permintaan tidak valid atau sesi telah kedaluwarsa.');
        $action=(string)($_POST['aksi']??'');$koneksi->begin_transaction();
        $master=spp_master_ensure_year($koneksi,$selectedYear,true);$masterId=(int)$master['id'];
        if($action==='simpan_tarif'){
            $amounts=$_POST['jumlah']??[];$rates=[];for($i=1;$i<=6;$i++)$rates[$i]=mspp_amount($amounts[$i]??0);
            $result=spp_master_save_rates($koneksi,$masterId,$rates);
            $_SESSION['flash']=['type'=>'success','msg'=>'Tarif tersimpan. '.$result['bills_updated'].' tagihan belum bayar diperbarui dan '.$result['bills_locked'].' tagihan berbayar dipertahankan.'];
        }elseif($action==='terbitkan'){
            $students=is_array($_POST['selected_students']??null)?$_POST['selected_students']:[];
            $starts=is_array($_POST['start_month']??null)?$_POST['start_month']:[];
            $result=spp_publish_students($koneksi,$masterId,$students,$starts);
            $message=$result['created'].' tagihan SPP baru berhasil diterbitkan.';
            if($result['existing'])$message.=' '.$result['existing'].' tagihan sudah tersedia.';
            if($result['ineligible'])$message.=' '.count($result['ineligible']).' siswa dilewati karena penempatannya belum valid.';
            $_SESSION['flash']=['type'=>'success','msg'=>$message];
        }elseif($action==='tutup'){
            if($master['status']!=='published')throw new RuntimeException('Hanya tahun SPP berstatus Terbit yang dapat ditutup.');
            $stmt=$koneksi->prepare("UPDATE master_spp_tahun SET status='closed',closed_at=NOW() WHERE id=?");$stmt->bind_param('i',$masterId);$stmt->execute();$stmt->close();
            spp_write_audit($koneksi,$masterId,null,'tutup_tahun',['status'=>'published'],['status'=>'closed']);
            $_SESSION['flash']=['type'=>'success','msg'=>'Tahun SPP ditutup. Tunggakan tetap dapat dibayar, sedangkan tarif telah dikunci.'];
        }elseif($action==='buka'){
            if($master['status']!=='closed')throw new RuntimeException('Hanya tahun SPP tertutup yang dapat dibuka kembali.');
            $stmt=$koneksi->prepare("UPDATE master_spp_tahun SET status='published',closed_at=NULL WHERE id=?");$stmt->bind_param('i',$masterId);$stmt->execute();$stmt->close();
            spp_write_audit($koneksi,$masterId,null,'buka_tahun',['status'=>'closed'],['status'=>'published']);
            $_SESSION['flash']=['type'=>'success','msg'=>'Tahun SPP dibuka kembali.'];
        }elseif($action==='batalkan_mulai_bulan'){
            $students=is_array($_POST['selected_students']??null)?array_values(array_unique(array_filter(array_map('strval',$_POST['selected_students'])))):[];
            $start=(string)($_POST['cancel_start_month']??'');$reason=trim((string)($_POST['cancel_reason']??''));
            if(!$students||!preg_match('/^(0[1-9]|1[0-2])$/',$start)||$reason==='')throw new RuntimeException('Pilih siswa, bulan efektif keluar, dan alasan pembatalan.');
            $periods=spp_academic_periods($selectedYear);$orders=[];foreach($periods as $p)$orders[$p['bulan'].'-'.$p['tahun']]=$p['order'];
            $startOrder=null;foreach($periods as $p)if($p['bulan']===$start){$startOrder=$p['order'];break;}
            $cancelled=0;
            $select=$koneksi->prepare("SELECT ts.id,ts.bulan,ts.tahun,EXISTS(SELECT 1 FROM spp_alokasi a JOIN spp_alokasi_batch ab ON ab.id=a.batch_id AND ab.status='active' WHERE a.tagihan_spp_id=ts.id) allocated FROM tagihan_spp ts WHERE ts.master_spp_tahun_id=? AND ts.no_induk=? AND ts.status='open' FOR UPDATE");
            $update=$koneksi->prepare("UPDATE tagihan_spp SET status='cancelled',cancel_reason=? WHERE id=?");
            foreach($students as $nis){$studentCancelled=0;$select->bind_param('is',$masterId,$nis);$select->execute();foreach($select->get_result()->fetch_all(MYSQLI_ASSOC) as $bill){$order=$orders[$bill['bulan'].'-'.$bill['tahun']]??-1;if($order<$startOrder||(int)$bill['allocated']===1)continue;$billId=(int)$bill['id'];$update->bind_param('si',$reason,$billId);$update->execute();$cancelled++;$studentCancelled++;}spp_write_audit($koneksi,$masterId,$nis,'batalkan_mulai_bulan',null,['bulan'=>$start,'alasan'=>$reason],$studentCancelled);}
            $select->close();$update->close();$_SESSION['flash']=['type'=>'success','msg'=>$cancelled.' tagihan belum bayar berhasil dibatalkan.'];
        }else throw new RuntimeException('Aksi Master SPP tidak dikenali.');
        $koneksi->commit();
    }catch(Throwable $e){try{$koneksi->rollback();}catch(Throwable $ignored){}$_SESSION['flash']=['type'=>'error','msg'=>$e->getMessage()];}
    mspp_redirect($selectedYear);
}

$master=spp_master_ensure_year($koneksi,$selectedYear);$masterId=(int)$master['id'];$rates=spp_master_rates($koneksi,$masterId);
$years=[];$currentStart=(int)substr(du_current_academic_year(),0,4);for($offset=-2;$offset<=3;$offset++){$start=$currentStart+$offset;$label=$start.'/'.($start+1);$years[$label]=$label;}$res=$koneksi->query('SELECT label FROM tahun_ajaran ORDER BY label DESC');while($r=$res->fetch_assoc())$years[$r['label']]=$r['label'];krsort($years);
$stmt=$koneksi->prepare("SELECT sta.no_induk,s.NAMA,s.NO_induk_diknas,sta.kelas,sta.master_kelas_id,sta.kelas_rombel_snapshot,sta.komite_mulai_bulan,s.potongan_spp_persen,s.is_active,
 COUNT(ts.id) bill_count,SUM(CASE WHEN ts.status='open' THEN 1 ELSE 0 END) open_count
 FROM siswa_tahun_ajaran sta JOIN tahun_ajaran ta ON ta.id=sta.tahun_ajaran_id JOIN siswa s ON s.NO_INDUK=sta.no_induk
 LEFT JOIN tagihan_spp ts ON ts.penempatan_id=sta.id WHERE ta.label=? AND sta.kelas IN ('1','2','3','4','5','6')
 GROUP BY sta.id,s.NAMA,s.NO_induk_diknas,s.potongan_spp_persen,s.is_active ORDER BY sta.kelas,sta.kelas_rombel_snapshot,s.NAMA");
$stmt->bind_param('s',$selectedYear);$stmt->execute();$students=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();
$stmt=$koneksi->prepare("SELECT COUNT(*) bills,SUM(CASE WHEN paid+0.001>=nominal_tagihan THEN 1 ELSE 0 END) paid_bills,SUM(CASE WHEN paid+0.001<nominal_tagihan AND status='open' THEN 1 ELSE 0 END) unpaid_bills FROM (SELECT ts.id,ts.nominal_tagihan,ts.status,COALESCE(SUM(CASE WHEN ab.status='active' THEN a.nominal_dari_bayar+a.nominal_dari_titipan ELSE 0 END),0) paid FROM tagihan_spp ts LEFT JOIN spp_alokasi a ON a.tagihan_spp_id=ts.id LEFT JOIN spp_alokasi_batch ab ON ab.id=a.batch_id WHERE ts.master_spp_tahun_id=? GROUP BY ts.id) x");
$stmt->bind_param('i',$masterId);$stmt->execute();$stats=$stmt->get_result()->fetch_assoc();$stmt->close();
$depositTotal=(float)($koneksi->query("SELECT COALESCE(SUM(CASE WHEN jenis IN ('masuk','koreksi_masuk') THEN nominal ELSE -nominal END),0) total FROM titipan_spp_mutasi")->fetch_assoc()['total']??0);
?>
<!doctype html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Master SPP | SistemSPP</title><link rel="icon" href="assets/img/favicon.png?v=2"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css?v=10.0"><script>(function(){var t=localStorage.getItem('spp_theme')||'dark';document.documentElement.setAttribute('data-theme',t);})();</script></head><body>
<div class="bg-orbs"><div class="orb orb-1"></div><div class="orb orb-2"></div><div class="orb orb-3"></div></div><div class="layout"><?php include 'includes/sidebar.php';?><main class="main-content">
<div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()" aria-label="Buka navigasi">☰</button><div class="topbar-title"><h2>Master Penerbitan SPP</h2><span class="breadcrumb">SistemSPP / Data Master / SPP</span></div><div class="clock-badge" id="liveClock">--:--:--</div></div>
<?php if($flash):?><div class="alert alert-<?=mspp_e($flash['type'])?>" id="flash-msg"><?=mspp_e($flash['msg'])?></div><?php endif;?>
<section class="main-card master-modern-shell spp-master-hero"><div class="master-modern-hero"><div><span class="recap-class-overline">Penerbitan SPP Juli–Juni</span><h1><?=mspp_e($selectedYear)?></h1><p>Tarif dan tagihan SPP berdiri sendiri dari penerbitan Daftar Ulang.</p></div><div class="master-modern-stats"><div><span>Tagihan</span><strong><?=number_format((int)($stats['bills']??0))?></strong></div><div><span>Belum Bayar</span><strong><?=number_format((int)($stats['unpaid_bills']??0))?></strong></div><div><span>Saldo Titipan</span><strong>Rp <?=mspp_money($depositTotal)?></strong></div></div><div class="du-master-year-tools"><form method="get"><select class="field-input field-select" name="tahun" onchange="this.form.submit()"><?php foreach($years as $year):?><option value="<?=mspp_e($year)?>" <?=$year===$selectedYear?'selected':''?>><?=mspp_e($year)?></option><?php endforeach;?></select></form><span class="recap-status <?=$master['status']==='draft'?'is-partial':($master['status']==='published'?'is-paid':'is-unpaid')?>"><?=mspp_e(strtoupper($master['status']))?></span></div></div></section>

<section class="main-card master-modern-card"><div class="card-title-row"><div><div class="card-title">Tarif Dasar per Tingkat</div><p class="payment-auto-note">Perubahan tarif memperbarui hanya tagihan yang belum pernah menerima pembayaran.</p></div></div><form method="post" id="spp-rate-form"><input type="hidden" name="csrf_token" value="<?=mspp_e($_SESSION['csrf_master_spp'])?>"><input type="hidden" name="aksi" value="simpan_tarif"><input type="hidden" name="tahun_ajaran" value="<?=mspp_e($selectedYear)?>"><div class="du-rate-grid"><?php for($i=1;$i<=6;$i++):?><label class="field-row"><span class="field-label">Kelas <?=$i?></span><input class="field-input rupiah-input" name="jumlah[<?=$i?>]" inputmode="numeric" value="<?=$rates[$i]>0?mspp_money($rates[$i]):''?>" placeholder="Rp 0" <?=$master['status']==='closed'?'disabled':''?>></label><?php endfor;?></div><?php if($master['status']!=='closed'):?><div class="action-bar"><button class="btn btn-primary" type="submit">Simpan Tarif</button></div><?php endif;?></form></section>

<section class="main-card master-modern-card"><div class="card-title-row"><div><div class="card-title">Pilih Siswa dan Terbitkan</div><p class="payment-auto-note">Hanya siswa yang sudah memiliki penempatan pada tahun ajaran ini yang dapat diterbitkan.</p></div></div>
<div class="promotion-filter-bar"><div class="search-box"><span>⌕</span><input type="search" id="spp-student-search" placeholder="Cari nama, NIS, atau rombel..."></div><select class="field-input field-select" id="spp-rombel-filter"><option value="">Semua rombel</option><?php $rombel=[];foreach($students as $s)$rombel[$s['kelas_rombel_snapshot']]=$s['kelas_rombel_snapshot'];ksort($rombel);foreach($rombel as $r):?><option value="<?=mspp_e($r)?>"><?=mspp_e($r)?></option><?php endforeach;?></select></div>
<form method="post" id="spp-publish-form"><input type="hidden" name="csrf_token" value="<?=mspp_e($_SESSION['csrf_master_spp'])?>"><input type="hidden" name="aksi" value="terbitkan"><input type="hidden" name="tahun_ajaran" value="<?=mspp_e($selectedYear)?>"><div class="promotion-selection-toolbar"><div><strong id="spp-visible-count"><?=count($students)?> siswa</strong><span id="spp-selected-count">0 siswa dipilih</span></div><div><button class="btn btn-ghost" type="button" id="spp-select-visible">Pilih yang Ditampilkan</button><button class="btn btn-ghost" type="button" id="spp-clear-selection">Kosongkan</button></div></div><div class="promotion-student-list" id="spp-student-list">
<?php foreach($students as $idx=>$s):$level=(int)$s['kelas'];$net=spp_net_tariff((float)$rates[$level],(float)$s['potongan_spp_persen']);$search=strtolower($s['NAMA'].' '.$s['no_induk'].' '.$s['kelas_rombel_snapshot']);?>
<article class="promotion-student-row spp-publish-row" data-search="<?=mspp_e($search)?>" data-rombel="<?=mspp_e($s['kelas_rombel_snapshot'])?>"><label class="promotion-student-check"><input type="checkbox" name="selected_students[]" value="<?=mspp_e($s['no_induk'])?>"><span></span></label><div class="promotion-student-identity"><strong><?=mspp_e($s['NAMA'])?></strong><small>NIS <?=mspp_e($s['no_induk'])?> · Potongan <?=mspp_e($s['potongan_spp_persen'])?>%</small></div><span class="kelas-badge"><?=mspp_e($s['kelas_rombel_snapshot'])?></span><div class="spp-rate-preview"><span>Tarif efektif</span><strong>Rp <?=mspp_money($net['net'])?></strong></div><label class="promotion-target-field"><span>Mulai tagihan</span><select class="field-input field-select" name="start_month[<?=mspp_e($s['no_induk'])?>]"><?php foreach(spp_academic_periods($selectedYear) as $p):?><option value="<?=$p['bulan']?>" <?=$p['bulan']===$s['komite_mulai_bulan']?'selected':''?>><?=mspp_e($p['label'])?></option><?php endforeach;?></select></label><span class="master-status <?=((int)$s['bill_count']>0)?'is-active':'is-inactive'?>"><?=((int)$s['bill_count']>0)?number_format((int)$s['bill_count']).' bulan':'Belum terbit'?></span></article>
<?php endforeach;?><?php if(!$students):?><div class="empty-state"><p>Belum ada penempatan siswa</p><span>Proses tahun ajaran pada Master Kelas/Rombel terlebih dahulu.</span></div><?php endif;?></div><?php if($master['status']!=='closed'&&$students):?><div class="promotion-submit-bar"><div><strong id="spp-submit-summary">Belum ada siswa dipilih</strong><span>Penerbitan tidak akan membuat tagihan ganda.</span></div><button class="btn btn-primary" id="spp-submit-button" type="submit" disabled>Terbitkan SPP</button></div><?php endif;?></form></section>

<?php if($master['status']!=='closed'&&$students):?><section class="main-card master-modern-card"><div class="card-title">Batalkan Tagihan Siswa Keluar</div><p class="payment-auto-note">Tagihan belum dibayar mulai bulan efektif keluar akan dibatalkan. Tagihan yang pernah menerima alokasi tetap dilindungi.</p><form method="post" class="fields-grid" onsubmit="return confirm('Batalkan tagihan SPP siswa mulai bulan terpilih?')"><input type="hidden" name="csrf_token" value="<?=mspp_e($_SESSION['csrf_master_spp'])?>"><input type="hidden" name="aksi" value="batalkan_mulai_bulan"><input type="hidden" name="tahun_ajaran" value="<?=mspp_e($selectedYear)?>"><div class="field-row"><label class="field-label">Siswa</label><select class="field-input field-select" name="selected_students[]" required><option value="">Pilih siswa</option><?php foreach($students as $s):?><option value="<?=mspp_e($s['no_induk'])?>"><?=mspp_e($s['NAMA'].' · '.$s['kelas_rombel_snapshot'])?></option><?php endforeach;?></select></div><div class="field-row"><label class="field-label">Efektif Mulai</label><select class="field-input field-select" name="cancel_start_month" required><?php foreach(spp_academic_periods($selectedYear) as $p):?><option value="<?=$p['bulan']?>"><?=mspp_e($p['label'])?></option><?php endforeach;?></select></div><div class="field-row full-span"><label class="field-label">Alasan</label><input class="field-input" name="cancel_reason" maxlength="255" required placeholder="Contoh: pindah sekolah efektif Oktober"></div><div class="action-bar full-span"><button class="btn btn-warning" type="submit">Batalkan Tagihan Belum Bayar</button></div></form></section><?php endif;?>

<section class="main-card master-modern-card"><div class="card-title-row"><div><div class="card-title">Status Tahun SPP</div><p class="payment-auto-note">Menutup tahun mengunci tarif. Tunggakan yang sudah terbit tetap bisa dilunasi.</p></div><div class="action-bar"><?php if($master['status']==='published'):?><form method="post" onsubmit="return confirm('Tutup tahun SPP ini?')"><input type="hidden" name="csrf_token" value="<?=mspp_e($_SESSION['csrf_master_spp'])?>"><input type="hidden" name="aksi" value="tutup"><input type="hidden" name="tahun_ajaran" value="<?=mspp_e($selectedYear)?>"><button class="btn btn-warning">Tutup Tahun</button></form><?php elseif($master['status']==='closed'):?><form method="post"><input type="hidden" name="csrf_token" value="<?=mspp_e($_SESSION['csrf_master_spp'])?>"><input type="hidden" name="aksi" value="buka"><input type="hidden" name="tahun_ajaran" value="<?=mspp_e($selectedYear)?>"><button class="btn btn-primary">Buka Kembali</button></form><?php endif;?></div></div></section>
</main></div><script src="assets/js/app.js?v=10.0"></script><script>document.querySelectorAll('.rupiah-input').forEach(e=>e.addEventListener('input',()=>{const n=e.value.replace(/\D/g,'');e.value=n?Number(n).toLocaleString('id-ID'):''}));document.getElementById('spp-rate-form')?.addEventListener('submit',e=>e.currentTarget.querySelectorAll('.rupiah-input').forEach(i=>i.value=i.value.replace(/\./g,'')));const rows=[...document.querySelectorAll('.spp-publish-row')],search=document.getElementById('spp-student-search'),filter=document.getElementById('spp-rombel-filter'),count=document.getElementById('spp-selected-count'),submit=document.getElementById('spp-submit-button');function refresh(){let visible=0,selected=0;rows.forEach(r=>{const show=(!search.value||r.dataset.search.includes(search.value.toLowerCase()))&&(!filter.value||r.dataset.rombel===filter.value);r.hidden=!show;if(show)visible++;if(r.querySelector('input[type=checkbox]').checked)selected++});document.getElementById('spp-visible-count').textContent=visible+' siswa ditampilkan';count.textContent=selected+' siswa dipilih';document.getElementById('spp-submit-summary').textContent=selected?selected+' siswa siap diterbitkan':'Belum ada siswa dipilih';if(submit)submit.disabled=!selected}search?.addEventListener('input',refresh);filter?.addEventListener('change',refresh);rows.forEach(r=>r.querySelector('input[type=checkbox]').addEventListener('change',refresh));document.getElementById('spp-select-visible')?.addEventListener('click',()=>{rows.filter(r=>!r.hidden).forEach(r=>r.querySelector('input').checked=true);refresh()});document.getElementById('spp-clear-selection')?.addEventListener('click',()=>{rows.forEach(r=>r.querySelector('input').checked=false);refresh()});refresh();autoHideFlash();</script></body></html>
