const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {execFileSync}=require('node:child_process');
if(process.env.SPP_TEST_ALLOW_MUTATION!=='1'||!/^db_spp_audit_[a-z0-9_]+$/.test(process.env.SPP_DB_NAME||''))throw Error('Audit clone required.');
const base=process.env.SPP_TEST_BASE_URL||'http://127.0.0.1:8771';if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base))throw Error('Loopback required.');
const data=JSON.parse(fs.readFileSync(process.env.SPP_AUTH_IDS_FILE,'utf8'));const password=fs.readFileSync(process.env.SPP_TEST_ADMIN_PASSWORD_FILE,'utf8').trim();
const output=process.env.SPP_AUTH_OUTPUT;fs.mkdirSync(output,{recursive:true});const {chromium}=require(process.env.SPP_PLAYWRIGHT_CORE||'playwright-core');
const fixture=(mode,unit)=>execFileSync(process.env.SPP_PHP_BIN||'php',[path.join(__dirname,'authorization_redesign_fixture.php'),mode,String(unit)],{encoding:'utf8',env:process.env});
const state=unit=>JSON.parse(fixture('state',unit));const url=p=>base+p;const account=(role,unit)=>data.accounts.find(a=>a.role===role&&(role==='super_admin'||Number(a.unit_id)===unit));
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];const pending=process.env.SPP_AUTH_VISUAL_ONLY==='1'?JSON.parse(fs.readFileSync(path.join(output,'pending.json'),'utf8')):{};
 try{
  async function login(role,unit){const context=await browser.newContext({viewport:{width:1600,height:1050}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
   const identity=await page.request.get(url('/tests/browser_clone_identity.php'));assert.equal((await identity.json()).database,process.env.SPP_DB_NAME);
   await page.goto(url('/login.php'));await page.locator('#username').fill(account(role,unit).username);await page.locator('#password').fill(password);await Promise.all([page.waitForNavigation(),page.locator('#btn-login').click()]);assert.ok(!page.url().endsWith('/login.php'));return page;}
  const superPage=await login('super_admin',1);
  async function unit(page,value){await page.goto(url('/otorisasi_transaksi.php?view=history'));await Promise.all([page.waitForNavigation(),page.locator('#sidebar-unit-select').selectOption(String(value))]);}
  for(const owner of process.env.SPP_AUTH_VISUAL_ONLY==='1'?[]:[1,2,3]){
   await unit(superPage,owner);const admin=await login('admin',owner);const cashier=await login('kasir',owner);const treasurer=await login('bendahara',owner);const payment=data.payments[owner];
   async function propose(page,amount){const before=state(owner);await page.goto(url('/pembayaran/edit.php?id='+payment.id));await page.waitForFunction(()=>!document.querySelector('#psb-input').readOnly);await page.locator('#psb-input').fill(String(amount));await page.locator('[name="authorization_reason"]').fill('Uji perubahan nominal oleh pemohon <>&');await Promise.all([page.waitForNavigation(),page.locator('#btn-update').click()]);const after=state(owner);assert.equal(Number(after.payment.total_jumlah),Number(before.payment.total_jumlah));assert.equal(after.requests.length,before.requests.length+1);return after.requests.at(-1).id;}
   async function selectRequest(page,id){await page.goto(url('/otorisasi_transaksi.php?view=queue&selected='+id));await page.locator('[data-auth-detail] input[name="request_id"][value="'+id+'"]').first().waitFor({state:'attached'});}
   async function decide(page,id,action){await selectRequest(page,id);const form=page.locator('[data-auth-detail] form').filter({has:page.locator(action==='approve'?'input[name="aksi"][value="otorisasi_setujui"]':'input[name="action"][value="'+action+'"]')});if(await form.locator('[name="decision_note"]').count())await form.locator('[name="decision_note"]').fill('Catatan keputusan <>&');await form.locator('button[type="submit"]').click();await page.locator('.auth-confirm-dialog[open]').waitFor();await Promise.all([page.waitForNavigation(),page.locator('[data-confirm-accept]').click()]);}
   const approved=await propose(cashier,200);await selectRequest(admin,approved);assert.equal(await admin.locator('button').filter({hasText:'Setujui dan Terapkan'}).count(),0);
   const token='forged-non-super-token';const initial=state(owner);
   for(const page of [admin,cashier,treasurer]){
    assert.equal((await page.request.post(url('/pembayaran/proses.php'),{form:{aksi:'otorisasi_setujui',request_id:String(approved),csrf_token:token},maxRedirects:0})).status(),403);
    assert.equal((await page.request.post(url('/otorisasi_transaksi.php'),{form:{action:'reject',request_id:String(approved),csrf_token:token,decision_note:'Forged'},maxRedirects:0})).status(),403);
   }
   assert.deepEqual(state(owner),initial);
   await selectRequest(superPage,approved);const superToken=await superPage.locator('[data-auth-detail] [name="csrf_token"]').first().inputValue();
   await superPage.request.post(url('/pembayaran/proses.php'),{form:{aksi:'otorisasi_setujui',request_id:String(approved),csrf_token:'wrong'},maxRedirects:0});assert.deepEqual(state(owner),initial);
   await decide(superPage,approved,'approve');assert.equal(Number(state(owner).payment.total_jumlah),200);assert.equal(state(owner).requests.at(-1).status,'approved');
   const done=state(owner);await superPage.request.post(url('/pembayaran/proses.php'),{form:{aksi:'otorisasi_setujui',request_id:String(approved),csrf_token:superToken},maxRedirects:0});assert.deepEqual(state(owner),done);
   const rejected=await propose(cashier,300);await decide(superPage,rejected,'reject');assert.equal(state(owner).requests.at(-1).status,'rejected');assert.equal(Number(state(owner).payment.total_jumlah),200);
   const cancelled=await propose(cashier,400);await decide(cashier,cancelled,'cancel');assert.equal(state(owner).requests.at(-1).status,'cancelled');
   const failed=await propose(cashier,500);fixture('stale',owner);await decide(superPage,failed,'approve');assert.equal(state(owner).requests.at(-1).status,'failed');assert.equal(Number(state(owner).payment.total_jumlah),200);
   fixture('pagination',owner);
   await cashier.goto(url('/pembayaran/lihat.php?search='+payment.nis+'&per_page=50&selected='+payment.id));await cashier.locator('.open-payment-delete-request[data-id="'+payment.id+'"]').click();await cashier.locator('#payment-delete-request-modal [name="authorization_reason"]').fill('Uji penghapusan melalui persetujuan Super Admin');await Promise.all([cashier.waitForNavigation(),cashier.locator('#payment-delete-request-modal button[type="submit"]').click()]);assert.ok(state(owner).payment);const deletion=state(owner).requests.at(-1).id;await decide(superPage,deletion,'approve');assert.equal(state(owner).payment,null);
   for(const page of [admin,treasurer,cashier]){const response=await page.request.get(url('/otorisasi_aktivitas.php?id='+payment.id));assert.equal(response.status(),200);const body=await response.json();assert.ok(body.events.some(e=>e.action==='deleted'));assert.ok(body.events.some(e=>e.action==='approved'&&e.role==='super_admin'));assert.ok(body.events.some(e=>e.action==='request_edit'&&e.role==='kasir'));assert.ok(body.events.some(e=>e.action==='failed'));assert.equal((await page.request.get(url('/otorisasi_detail.php?view=history&id='+payment.id+'&unit_id='+(owner===1?2:1)))).status(),404);}
   assert.equal((await cashier.request.get(url('/otorisasi_aktivitas.php?id='+(9100000+owner*100+1)))).status(),404);
   assert.equal((await admin.request.get(url('/otorisasi_detail.php?view=history&id='+data.payments[owner===1?2:1].id))).status(),404);
   assert.equal((await admin.request.get(url('/otorisasi_export_pdf.php?output=pdf&q='+payment.nis))).status(),403);const filtered=await superPage.request.get(url('/otorisasi_export_pdf.php?output=pdf&q='+payment.nis));assert.equal(filtered.status(),200);assert.ok((await filtered.body()).subarray(0,5).toString()==='%PDF-');fs.writeFileSync(path.join(output,'history-'+owner+'.pdf'),await filtered.body());
   await admin.goto(url('/otorisasi_transaksi.php?view=history&q='+payment.nis));await admin.locator('.auth-full-history').click();await admin.locator('.payment-activity-event').first().waitFor();assert.ok((await admin.locator('#payment-activity-dialog').innerText()).includes('Pengajuan edit'));await admin.locator('[data-close-activity]').click();
   pending[owner]=JSON.parse(fixture('pending',owner));fs.writeFileSync(path.join(output,'pending.json'),JSON.stringify(pending));
   await admin.goto(url('/otorisasi_transaksi.php'));assert.ok(await admin.locator('[data-auth-record]').count());assert.equal(await admin.getByRole('button',{name:'Setujui dan Terapkan',exact:true}).count(),0);
   await admin.context().close();await cashier.context().close();await treasurer.context().close();console.log('OK unit '+owner+': Admin/cashier requests; super decisions; forged/duplicate/CSRF denied; deletion journal and PDF retained.');
  }
  for(const scope of [1,2,3,0]){
   await unit(superPage,scope);
   for(const view of ['history','queue'])for(const width of [1600,768,390])for(const theme of ['light','dark']){
    await superPage.setViewportSize({width,height:1050});await superPage.goto(url('/otorisasi_transaksi.php?view='+view));await superPage.evaluate(t=>{document.documentElement.dataset.theme=t;localStorage.setItem('theme',t);},theme);
    assert.ok(await superPage.locator('[data-auth-record]').count());assert.ok(await superPage.locator('[data-auth-detail]').innerText());assert.equal(await superPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'Horizontal overflow '+scope+'/'+width+'/'+theme);
    await superPage.waitForTimeout(650);await superPage.screenshot({path:path.join(output,`authorization-${scope}-${view}-${width}-${theme}.png`),fullPage:true});
   }
   await superPage.setViewportSize({width:1600,height:1000});await superPage.goto(url('/otorisasi_transaksi.php?view=history'));assert.equal(await superPage.locator('[data-auth-record]').count(),25);const first=await superPage.locator('[data-auth-detail]').innerText();await superPage.locator('[data-auth-next]').click();await superPage.waitForFunction(()=>!document.querySelector('[data-auth-detail]').hasAttribute('aria-busy'));assert.notEqual(await superPage.locator('[data-auth-detail]').innerText(),first);await superPage.locator('.auth-full-history').click();await superPage.locator('.payment-activity-event').first().waitFor();await superPage.locator('[data-close-activity]').click();
   await superPage.getByRole('link',{name:'Berikutnya',exact:true}).click();assert.ok(await superPage.locator('[data-auth-record]').count());
   const pdf=await superPage.request.get(url('/otorisasi_export_pdf.php?output=pdf&q=UJI%20REDESIGN%20PAGINATION'));assert.equal(pdf.status(),200);fs.writeFileSync(path.join(output,'pagination-'+scope+'.pdf'),await pdf.body());
   const empty=await superPage.request.get(url('/otorisasi_export_pdf.php?output=pdf&q=NEVER_MATCH_AUTH_123'));assert.equal(empty.status(),200);fs.writeFileSync(path.join(output,'empty-'+scope+'.pdf'),await empty.body());
   const preview=await superPage.request.get(url('/otorisasi_export_pdf.php?q=UJI%20REDESIGN%20PAGINATION'));assert.equal(preview.status(),200);assert.ok((await preview.text()).includes('Preview PDF'));
   if(scope===1||scope===0){const long=await superPage.request.get(url('/otorisasi_export_pdf.php?output=pdf&q=LONGAUTH1'));assert.equal(long.status(),200);fs.writeFileSync(path.join(output,'long-'+scope+'.pdf'),await long.body());}
   for(const endpoint of ['otorisasi_transaksi.php?view=history','otorisasi_export_pdf.php?output=pdf'])for(const invalid of ['&kind=unavailable','&status%5B0%5D=unavailable'])assert.equal((await superPage.request.get(url('/'+endpoint+invalid))).status(),400);
   if(scope===0){assert.equal(await superPage.locator('[name="aksi"][value="otorisasi_setujui"]').count(),0);const resp=await superPage.request.post(url('/pembayaran/proses.php'),{form:{aksi:'otorisasi_setujui',request_id:String(pending[1].request_id)},maxRedirects:0});assert.equal(resp.status(),409);}
  }
  await unit(superPage,1);await superPage.goto(url('/otorisasi_transaksi.php?view=history'));await superPage.locator('[data-auth-record]').nth(2).click();await superPage.locator('[data-auth-record]').nth(3).click();await superPage.waitForFunction(()=>!document.querySelector('[data-auth-detail]').hasAttribute('aria-busy'));const ref=await superPage.locator('[data-auth-record].is-selected .auth-record-identity strong').innerText();assert.ok((await superPage.locator('[data-auth-detail]').innerText()).includes(ref));
  const nojs=await browser.newContext({javaScriptEnabled:false});const np=await nojs.newPage();await np.goto(url('/login.php'));await np.locator('#username').fill(account('super_admin',1).username);await np.locator('#password').fill(password);await Promise.all([np.waitForNavigation(),np.locator('#btn-login').click()]);await np.goto(url('/otorisasi_transaksi.php?view=history'));await np.locator('[data-auth-record]').nth(2).click({force:true});assert.ok((await np.locator('[data-auth-detail]').innerText()).includes(await np.locator('.is-selected .auth-record-identity strong').innerText()));await nojs.close();
  assert.deepEqual(errors,[]);console.log('OK: four scopes, both tabs, 3 sizes, both themes; AJAX/dialog/navigation/no-JS; all-pages PDF and empty output.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
