const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.SPP_PLAYWRIGHT_CORE||'playwright-core');
const base=process.env.SPP_TEST_BASE_URL,output=process.env.SPP_XLSX_TEST_OUTPUT;
assert.match(process.env.SPP_DB_NAME||'',/^db_spp_audit_/);
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(new URL('login.php',base).href);
  await page.locator('#username').fill('superadmin');
  await page.locator('#password').fill(fs.readFileSync(process.env.SPP_TEST_ADMIN_PASSWORD_FILE,'utf8').trim());
  await Promise.all([page.waitForNavigation(),page.locator('#btn-login').click()]);
  for(const unit of [1,2,3]){
    await page.goto(new URL('dashboard.php',base).href);
    await Promise.all([page.waitForNavigation(),page.locator('#sidebar-unit-select').selectOption(String(unit))]);
    await page.goto(new URL('siswa/daftar.php',base).href);
    await page.locator('[data-class-picker-button]').click();
    const classMenu=page.locator('[data-class-picker-panel]');
    assert.equal(await classMenu.locator('input[type=search]').count(),0);assert.equal(await classMenu.locator('.spp-dropdown-note').innerText(),'Pilih satu opsi');const classRect=await classMenu.boundingBox();assert.ok(classRect.width<600&&classRect.x+classRect.width<=1440&&classRect.y+classRect.height<=1000,'Class panel must stay anchored');
    const classOption=classMenu.locator('[data-class-picker-option]:visible:not(:disabled)').first();
    const value=await classOption.getAttribute('data-value'),rate=await classOption.getAttribute('data-spp-base');await classOption.click();
    assert.equal(await page.locator('#kelas-baru').inputValue(),value);assert.equal(await page.locator('#student-spp-base').getAttribute('data-base'),rate);
    await page.locator('[data-class-picker-button]').click();await page.keyboard.press('Escape');assert.equal(await page.locator('[data-class-picker]').evaluate(o=>o.classList.contains('is-open')),false);
    const legacy=JSON.parse(fs.readFileSync(path.join(output,'dropdown-legacy.json'),'utf8'))[unit];if(legacy){await page.goto(new URL('siswa/aktivasi_legacy.php?id='+legacy,base).href);for(const trigger of await page.locator('.spp-select-trigger').all()){await trigger.click();const panel=page.locator('.spp-dropdown-panel:visible');assert.equal(await panel.locator('.spp-dropdown-note').innerText(),'Pilih satu opsi');assert.equal(await panel.locator('input[type=search]').count(),0);await page.keyboard.press('Escape');}}
    assert.ok(await classMenu.isHidden());
    await page.goto(new URL('pembayaran/form.php',base).href);
    const year=page.locator('#tahun-bayar');await year.click();
    const yearMenu=page.locator('.payment-year-options');
    assert.equal(await yearMenu.locator('input[type=search]').count(),0);await yearMenu.locator('.payment-year-option').filter({hasText:/^2027$/}).click();
    assert.equal(await year.inputValue(),'2027');assert.ok(await yearMenu.isHidden());
    // Client-only fixture exercises the same native source and dynamic row code, without saving.
    await page.evaluate(()=>{const select=document.querySelector('.biaya-lain-select');
      select.innerHTML='<option value="">Belum ada tagihan</option><option value="qa-long">Biaya kegiatan dengan nama sangat panjang untuk memeriksa pembungkusan teks pada dropdown pembayaran</option><option value="qa-paid" disabled>Seragam (Lunas)</option>';
      window.syncSppDropdowns();});
    const fee=page.locator('.biaya-lain-select').first(),feeButton=fee.locator('..').locator('.spp-select-trigger');
    await feeButton.click();const panel=page.locator('.spp-dropdown-panel:visible');
    assert.equal(await panel.getByRole('option',{name:'Seragam Lunas',exact:false}).isDisabled(),true);
    assert.equal(await panel.locator('input[type=search]').count(),0);await panel.getByRole('option',{name:/Biaya kegiatan/}).click();
    assert.equal(await fee.inputValue(),'qa-long');assert.match(await feeButton.innerText(),/Biaya kegiatan/);assert.ok(await feeButton.evaluate(b=>b.scrollHeight<=b.clientHeight+2),'Long option title must not be clipped');
    await page.evaluate(()=>{const s=document.querySelector('.biaya-lain-select');s.value='';s.disabled=true;});
    await assert.doesNotReject(()=>feeButton.waitFor({state:'visible'}));assert.ok(await feeButton.isDisabled());
    await page.evaluate(()=>{document.querySelector('.biaya-lain-select').disabled=false;window.addBiayaLainRow();});
    await page.waitForFunction(()=>document.querySelectorAll('#biaya-lain-list .spp-select-trigger').length===2);
    assert.equal(await page.locator('#biaya-lain-list .spp-select').count(),2);
    await page.locator('.btn-remove-biaya-lain').last().click();
    await page.waitForFunction(()=>document.querySelectorAll('#biaya-lain-list .spp-select').length===1);
    await page.locator('#sistem-pembayaran').evaluate(s=>{s.value='VA';});
    const method=page.locator('#sistem-pembayaran').locator('..').locator('.spp-select-trigger');
    assert.match(await method.innerText(),/VA/);
    await page.locator('#sistem-pembayaran').evaluate(s=>s.form.reset());
    await page.waitForFunction(()=>document.querySelector('#sistem-pembayaran').value==='');
    assert.match(await method.innerText(),/Pilih metode/);
    // Actual published bill controls and the edit page use the same enhancement.
    const student=await page.locator('#siswa-list option').evaluateAll(options=>options.find(o=>o.dataset.nama.includes('Demo')&&o.dataset.kelas!=='PSB')?.value||options[0]?.value);
    await page.locator('#siswa-search').fill(student);
    await page.waitForFunction(()=>document.querySelector('#disp-nis').value!=='');
    await page.locator('#du-selector-trigger').click();
    assert.equal(await page.locator('#du-selector-menu input[type=search]').count(),0);assert.equal(await page.locator('#du-selector-menu .spp-dropdown-note').innerText(),'Pilih satu opsi');
    await page.keyboard.press('Escape');
    await page.goto(new URL('pembayaran/lihat.php?tanggal_awal=2026-09-01&tanggal_akhir=2026-10-06',base).href);
    const edit=page.locator('a[href*="edit.php?id="]').first();assert.ok(await edit.count());
    const editUrl=await edit.getAttribute('href');await page.goto(new URL(editUrl,page.url()).href);
    assert.equal(await page.locator('select:not(.spp-select-native):not([aria-hidden=true]):not([data-native-select])').count(),0);
    await page.setViewportSize({width:390,height:950});
    const editFee=page.locator('.biaya-lain-select').first().locator('..').locator('.spp-select-trigger');
    await editFee.scrollIntoViewIfNeeded();await editFee.click();
    const rect=await page.locator('.spp-dropdown-panel:visible').boundingBox();
    assert.ok(rect.x>=0&&rect.x+rect.width<=391&&rect.y>=0&&rect.y+rect.height<=951);
    await page.screenshot({path:path.join(output,'edit-dropdown-'+unit+'.png')});
    await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});
    await page.goto(new URL('laporan/template.php?template=per-item&kategori=spp&unit=active',base).href);
    await page.locator('.report-month-range-button').click();
    const monthPicker=page.locator('[data-month-range-picker]');
    await monthPicker.locator('[data-month-range-start]').locator('..').locator('.spp-select-trigger').click();
    await page.locator('.spp-dropdown-panel:visible').getByRole('option',{name:'Agustus',exact:true}).click();
    assert.ok(await monthPicker.locator('.report-month-range-popover').isVisible(),'Nested month popover must remain open');
    await monthPicker.locator('[data-month-range-end]').locator('..').locator('.spp-select-trigger').click();
    await page.locator('.spp-dropdown-panel:visible').getByRole('option',{name:'September',exact:true}).click();
    await monthPicker.locator('[data-month-range-apply]').click();
    assert.equal(await monthPicker.locator('input[name=bulan_awal]').inputValue(),'08');
    assert.equal(await monthPicker.locator('input[name=bulan_akhir]').inputValue(),'09');
    console.log('PASS: unit '+unit+' class/year, dynamic rows, disabled/lunas, automatic values, reset, DU and edit');
  }
  // A select inserted into a modal stays above the dialog and inside a narrow screen.
  await page.evaluate(()=>{const dialog=document.createElement('dialog');dialog.id='qa-dropdown-dialog';dialog.innerHTML='<label>Contoh dalam modal<select><option value="a">Awal</option><option value="b">Pilihan kedua</option></select></label>';document.body.append(dialog);dialog.showModal();});
  await page.locator('#qa-dropdown-dialog .spp-select-trigger').click();
  await page.locator('.spp-dropdown-panel:visible').getByRole('option',{name:'Pilihan kedua',exact:true}).click();
  assert.equal(await page.locator('#qa-dropdown-dialog select').inputValue(),'b');
  assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
