const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.SPP_PLAYWRIGHT_CORE||'playwright-core');
const base=process.env.SPP_TEST_BASE_URL,output=process.env.SPP_XLSX_TEST_OUTPUT,password=fs.readFileSync(process.env.SPP_TEST_ADMIN_PASSWORD_FILE,'utf8').trim();
assert.match(process.env.SPP_DB_NAME||'',/^db_spp_audit_/);assert.ok(output&&base);
const templates=['status','penerimaan','spp-tahunan','per-item','tabungan-siswa','saldo-tabungan','riwayat-tagihan','tunggakan-siswa','setoran','kas-tabungan'];
const pages=['dashboard.php','siswa/daftar.php','master_kelas.php','master_spp.php','master_daftar_ulang.php','master_biaya_lain.php','pembayaran/form.php','pembayaran/lihat.php','pembayaran/riwayat_daftar_ulang.php','otorisasi_transaksi.php','tabungan/riwayat.php','tabungan/cetak.php','laporan/index.php','laporan/surat_orang_tua.php','role_management.php','backup_restore.php'];
async function get(page,url){const response=await page.request.get(new URL(url,base).href);assert.equal(response.status(),200,url);return response;}
async function download(page,url,name){const response=await get(page,url);assert.match(response.headers()['content-type'],/spreadsheetml.sheet/);assert.match(response.headers()['content-disposition'],/\.xlsx/);const data=await response.body();assert.equal(data.subarray(0,2).toString(),'PK');fs.writeFileSync(path.join(output,name+'.xlsx'),data);}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto(new URL('login.php',base).href);await page.locator('#username').fill('superadmin');await page.locator('#password').fill(password);await Promise.all([page.waitForNavigation(),page.locator('#btn-login').click()]);assert.ok(!page.url().endsWith('login.php'));
  for(const unit of [1,2,3,0]){await page.goto(new URL('dashboard.php',base).href);await Promise.all([page.waitForNavigation(),page.locator('#sidebar-unit-select').selectOption(String(unit))]);
    for(const template of templates){const query='template='+template+'&unit=active&tanggal_awal=2026-09-01&tanggal_akhir=2026-10-06';await download(page,'laporan/export_global.php?'+query+'&format=excel&download=1',unit+'-'+template);const preview=await get(page,'laporan/export_global.php?'+query+'&format=excel');assert.ok((await preview.text()).includes('Preview EXCEL'));}
    await download(page,'laporan/export_excel.php?download=1&tanggal_awal=2026-09-01&tanggal_akhir=2026-10-06',unit+'-umum');await download(page,'siswa/export_excel.php?download=1&status=all',unit+'-siswa');
    for(const [width,theme] of [[1440,'light'],[768,'dark'],[390,'light'],[390,'dark']]){await page.setViewportSize({width,height:950});await page.addInitScript(t=>localStorage.setItem('spp_theme',t),theme);await page.goto(new URL('laporan/template.php?template=status&unit=active',base).href);const select=page.locator('select[name="kategori[]"]');const trigger=select.locator('..').locator('.spp-select-trigger');await trigger.scrollIntoViewIfNeeded();await trigger.click();const panel=page.locator('.spp-dropdown-panel:visible');assert.equal(await panel.locator('input[type=search]').count(),0);await panel.locator('.spp-multi-all input').check();await panel.locator('.spp-multi-all input').uncheck();await panel.locator('.spp-multi-option').filter({hasText:/^Komite$/}).locator('input').check();await panel.getByRole('button',{name:'Terapkan',exact:true}).click();assert.deepEqual(await select.evaluate(s=>[...s.selectedOptions].map(o=>o.value)),['komite']);assert.equal(await trigger.getAttribute('aria-expanded'),'false');await trigger.focus();await page.keyboard.press('ArrowDown');assert.ok((await page.locator('.spp-dropdown-panel:visible').count())===1);await page.keyboard.press('Escape');assert.equal(await trigger.getAttribute('aria-expanded'),'false');await trigger.click();const rect=await page.locator('.spp-dropdown-panel:visible').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=width+1&&rect.y>=0&&rect.y+rect.height<=951,'Panel must fit viewport');await page.screenshot({path:path.join(output,'dropdown-'+unit+'-'+width+'-'+theme+'.png')});await page.keyboard.press('Escape');}
    await page.setViewportSize({width:1440,height:1000});
    for(const name of unit===0?pages.filter(p=>!['pembayaran/form.php','master_spp.php','master_daftar_ulang.php','master_biaya_lain.php','backup_restore.php'].includes(p)):pages){await page.goto(new URL(name,base).href);await page.waitForLoadState('domcontentloaded');assert.equal(await page.locator('select:not(.spp-select-native):not([aria-hidden=true]):not([data-native-select])').count(),0,'Unenhanced dropdown: '+name);const first=page.locator('.spp-select-trigger:not(:disabled)').first();if(await first.count()){await first.scrollIntoViewIfNeeded();await first.click();assert.ok(await page.locator('.spp-dropdown-panel:visible').count());await page.keyboard.press('Escape');}}
    await page.goto(new URL('laporan/export_global.php?template=setoran&unit=active&format=excel&tanggal_awal=2026-09-01&tanggal_akhir=2026-10-06',base).href);await page.screenshot({path:path.join(output,'preview-setoran-'+unit+'.png'),fullPage:true});console.log('PASS: unit '+unit+' exports, previews, dropdowns, keyboard, themes and viewport coverage');
  }
  assert.deepEqual(errors,[],'Browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
