const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
if(process.env.SPP_TEST_ALLOW_MUTATION!=='1'||!/^db_spp_audit_[a-z0-9_]+$/.test(process.env.SPP_DB_NAME||''))throw Error('Audit clone required.');
const base=process.env.SPP_TEST_BASE_URL||'http://127.0.0.1:8771';if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base))throw Error('Loopback required.');
const data=JSON.parse(fs.readFileSync(process.env.SPP_HISTORY_IDS_FILE,'utf8')),password=fs.readFileSync(process.env.SPP_TEST_ADMIN_PASSWORD_FILE,'utf8').trim();
const output=process.env.SPP_AUTH_OUTPUT;fs.mkdirSync(output,{recursive:true});const {chromium}=require(process.env.SPP_PLAYWRIGHT_CORE||'playwright-core');
const fixture=(mode,unit,id,active)=>execFileSync(process.env.SPP_PHP_BIN||'php',[path.join(__dirname,'payment_history_redesign_fixture.php'),mode,String(unit),String(id||''),String(active??'')],{encoding:'utf8',env:process.env});
const state=(unit,id)=>JSON.parse(fixture('state',unit,id));const url=p=>base+p;const account=(role,unit)=>role==='super_admin'?data.super:data.accounts[unit][role];
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];let nativeDialogs=0;
try{
 async function login(role,unit,options={}){const context=await browser.newContext({viewport:{width:1600,height:1050},...options}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{nativeDialogs++;d.dismiss();});assert.equal((await (await page.request.get(url('/tests/browser_clone_identity.php'))).json()).database,process.env.SPP_DB_NAME);await page.goto(url('/login.php'));await page.locator('#username').fill(account(role,unit).username);await page.locator('#password').fill(password);await Promise.all([page.waitForNavigation(),page.locator('#btn-login').click()]);assert.ok(!page.url().endsWith('/login.php'));return page;}
 const superPage=await login('super_admin',1);
 async function unit(page,value){await page.goto(url('/pembayaran/lihat.php'));await Promise.all([page.waitForNavigation(),page.locator('#sidebar-unit-select').selectOption(String(value))]);}
 async function detail(page,unit,id,view='active'){return (await page.request.get(url('/pembayaran/detail.php?view='+view+'&id='+id+'&unit_id='+unit))).json();}
 async function open(page,unit,id,view='active'){await page.goto(url('/pembayaran/lihat.php?per_page=50&view='+view+'&search='+data.payments[unit].kasir.nis+'&selected='+id));await page.locator('[data-payment-detail]').waitFor();}
 async function propose(page,id,amount){await page.goto(url('/pembayaran/edit.php?id='+id));await page.waitForFunction(()=>!document.querySelector('#psb-input').readOnly);await page.locator('#psb-input').fill(String(amount));await page.locator('[name="authorization_reason"]').fill('Uji pengajuan pemilik <>&');await Promise.all([page.waitForNavigation(),page.locator('#btn-update').click()]);}
 async function decide(page,id,action){await page.goto(url('/otorisasi_transaksi.php?view=queue&selected='+id));const selector=action==='approve'?'[name="aksi"][value="otorisasi_setujui"]':'[name="action"][value="'+action+'"]';const form=page.locator('[data-auth-detail] form').filter({has:page.locator(selector)});if(await form.locator('[name="decision_note"]').count())await form.locator('[name="decision_note"]').fill('Uji keputusan <>&');await form.locator('button[type="submit"]').click();await page.locator('.auth-confirm-dialog[open]').waitFor();await Promise.all([page.waitForNavigation(),page.locator('[data-confirm-accept]').click()]);}
 for(const u of [1,2,3]){
  await unit(superPage,u);const admin=await login('admin',u),cash=await login('kasir',u),cash2=await login('kasir2',u),bend=await login('bendahara',u);const p=data.payments[u];
  for(const [role,page] of [['admin',admin],['kasir',cash],['kasir2',cash2],['bendahara',bend]]){
   await open(page,u,p[role].id);const own=await detail(page,u,p[role].id);assert.equal(own.ok,true);assert.equal(own.capabilities.can_print,true);assert.equal(own.capabilities.can_edit,role!=='bendahara');assert.equal(own.capabilities.owner_id,Number(account(role,u).id));
   assert.equal(await page.locator('[data-payment-record]').count(),30,'All operator transactions stay visible.');assert.equal(await page.locator('[data-print-payment]').count(),1);
   for(const other of ['super_admin','admin','kasir','kasir2','bendahara','unknown'].filter(v=>v!==role)){
    const foreign=await detail(page,u,p[other].id);assert.equal(foreign.capabilities.can_print,false);assert.equal(foreign.capabilities.can_edit,false);assert.equal(foreign.capabilities.locked,true);assert.ok(foreign.html.includes('Riwayat Aktivitas'));
    assert.equal((await page.request.get(url('/laporan/cetak_struk.php?id='+p[other].id),{maxRedirects:0})).status(),403);
    if(role!=='bendahara')assert.equal((await page.request.get(url('/pembayaran/edit.php?id='+p[other].id),{maxRedirects:0})).status(),403);
   }
   const before=state(u,p.super_admin.id);const csrf=await page.locator('#payment-delete-request-modal [name="csrf_token"]').inputValue();
   if(role!=='bendahara')for(const aksi of ['hapus','update'])assert.equal((await page.request.post(url('/pembayaran/proses.php'),{form:{aksi,id:String(p.super_admin.id),csrf_token:csrf,authorization_reason:'Uji serangan pemilik asing'},maxRedirects:0})).status(),403);
   assert.deepEqual(state(u,p.super_admin.id),before);
   for(const outputType of ['preview','pdf','inline'])assert.equal((await page.request.get(url('/otorisasi_export_pdf.php?output='+outputType))).status(),403);
   await page.goto(url('/otorisasi_transaksi.php?view=history'));assert.equal(await page.locator('a[href*="otorisasi_export_pdf"]').count(),0);
   assert.equal((await page.request.get(url('/pembayaran/detail.php?id='+p.kasir.id+'&unit_id='+(u===1?2:1)))).status(),404);
   assert.equal((await page.request.get(url('/pembayaran/aktivitas.php?id='+p.kasir.id+'&unit_id='+(u===1?2:1)))).status(),404);
  }
  assert.equal((await cash.request.get(url('/laporan/cetak_struk_tahunan.php?batch='+data.batches[u].own.token))).status(),200);
  assert.equal((await cash.request.get(url('/laporan/cetak_struk_tahunan.php?batch='+data.batches[u].mixed.token))).status(),403);
  fixture('shared',u,p.kasir.id);const baseState=state(u,p.kasir.id);
  await propose(cash,p.kasir.id,200);let req=state(u,p.kasir.id).requests.at(-1);assert.equal(state(u,p.kasir.id).payment.total_jumlah,baseState.payment.total_jumlah);
  await superPage.goto(url('/otorisasi_transaksi.php?view=queue&selected='+req.id));await superPage.locator('[name="decision_note"]').first().fill('Konfirmasi aman');await superPage.getByRole('button',{name:'Setujui dan Terapkan',exact:true}).click();await superPage.locator('.auth-confirm-dialog[open]').waitFor();assert.ok((await superPage.locator('.auth-confirm-dialog').innerText()).includes('Pembuat awal'));await superPage.keyboard.press('Escape');assert.equal(state(u,p.kasir.id).requests.at(-1).status,'pending');
  const token=await superPage.locator('[name="csrf_token"]').first().inputValue();await superPage.request.post(url('/pembayaran/proses.php'),{form:{aksi:'otorisasi_setujui',request_id:String(req.id),csrf_token:'wrong'},maxRedirects:0});assert.equal(state(u,p.kasir.id).requests.at(-1).status,'pending');
  await decide(superPage,req.id,'approve');assert.equal(Number(state(u,p.kasir.id).payment.total_jumlah),200);const after=state(u,p.kasir.id);await superPage.request.post(url('/pembayaran/proses.php'),{form:{aksi:'otorisasi_setujui',request_id:String(req.id),csrf_token:token},maxRedirects:0});assert.deepEqual(state(u,p.kasir.id),after);assert.equal((await detail(cash,u,p.kasir.id)).capabilities.owner_id,Number(account('kasir',u).id));
  await propose(admin,p.admin.id,200);req=state(u,p.admin.id).requests.at(-1);await decide(superPage,req.id,'reject');assert.equal(state(u,p.admin.id).requests.at(-1).status,'rejected');assert.equal(Number(state(u,p.admin.id).payment.total_jumlah),100);
  await propose(cash,p.kasir.id,300);req=state(u,p.kasir.id).requests.at(-1);await decide(cash,req.id,'cancel');assert.equal(state(u,p.kasir.id).requests.at(-1).status,'cancelled');
  await propose(cash,p.kasir.id,400);req=state(u,p.kasir.id).requests.at(-1);fixture('stale',u,p.kasir.id);await decide(superPage,req.id,'approve');assert.equal(state(u,p.kasir.id).requests.at(-1).status,'failed');
  await superPage.goto(url('/pembayaran/edit.php?id='+p.kasir.id));await superPage.waitForFunction(()=>!document.querySelector('#psb-input').readOnly);await superPage.locator('#psb-input').fill('100');await Promise.all([superPage.waitForNavigation(),superPage.locator('#btn-update').click()]);assert.equal(Number(state(u,p.kasir.id).payment.user_id),Number(data.super.id));assert.equal((await detail(cash,u,p.kasir.id)).capabilities.can_edit,true);assert.equal((await detail(admin,u,p.kasir.id)).capabilities.can_edit,false);
  await open(admin,u,p.admin.id);await admin.locator('.open-payment-delete-request').click();await admin.locator('#payment-delete-request-modal [name="authorization_reason"]').fill('Uji penghapusan milik Admin');await Promise.all([admin.waitForNavigation(),admin.locator('#payment-delete-request-modal button[type="submit"]').click()]);req=state(u,p.admin.id).requests.at(-1);assert.ok(state(u,p.admin.id).payment);
  await superPage.goto(url('/otorisasi_transaksi.php?view=queue&selected='+req.id));await superPage.getByRole('button',{name:'Setujui dan Terapkan',exact:true}).click();await superPage.locator('.auth-confirm-dialog[open]').waitFor();assert.equal(await superPage.locator('.auth-confirm-dialog').getAttribute('data-danger'),'true');assert.ok((await superPage.locator('.auth-confirm-dialog').innerText()).includes('jurnal aktivitas tetap tersimpan'));await superPage.locator('[data-confirm-cancel]').click();assert.ok(state(u,p.admin.id).payment);await decide(superPage,req.id,'approve');assert.equal(state(u,p.admin.id).payment,null);
  for(const page of [admin,cash,bend,superPage]){const archive=await detail(page,u,p.admin.id,'deleted');assert.equal(archive.ok,true);assert.equal(archive.capabilities.can_print,false);assert.equal(archive.capabilities.can_edit,false);assert.ok(archive.html.includes('Dihapus oleh'));assert.equal((await page.request.get(url('/pembayaran/detail.php?id='+p.admin.id))).status(),404);}
  await open(cash,u,p.kasir.id);await cash.locator('.open-payment-activity').click();await cash.locator('.payment-activity-event').first().waitFor();assert.ok((await cash.locator('#payment-activity-dialog').innerText()).includes('Usulan:'));await cash.locator('[data-close-activity]').click();
  fixture('inactive',u,p.kasir2.id,0);assert.equal((await cash2.request.get(url('/pembayaran/detail.php?id='+p.kasir2.id))).status(),403);fixture('inactive',u,p.kasir2.id,1);
  for(const page of [admin,cash,cash2,bend])await page.context().close();console.log('OK unit '+u+': ownership, locked actions/receipts/batches, requests/decisions, archive, inactive, PDF policy.');
 }
 for(const scope of [1,2,3,0]){
  await unit(superPage,scope);
  for(const view of ['active','deleted'])for(const width of [1600,768,390])for(const theme of ['light','dark']){
   await superPage.setViewportSize({width,height:1000});await superPage.goto(url('/pembayaran/lihat.php?view='+view));await superPage.evaluate(t=>document.documentElement.dataset.theme=t,theme);await superPage.waitForTimeout(250);assert.ok(await superPage.locator('[data-payment-record]').count());assert.equal(await superPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'Overflow '+scope+'/'+view+'/'+width+'/'+theme);assert.ok(!(await superPage.locator('body').innerText()).includes('Warning:'));await superPage.screenshot({path:path.join(output,`payment-history-${scope}-${view}-${width}-${theme}.png`),fullPage:true});
  }
  const pdf=await superPage.request.get(url('/otorisasi_export_pdf.php?output=pdf&q=UJI%20RIWAYAT'));assert.equal(pdf.status(),200);assert.equal((await pdf.body()).subarray(0,5).toString(),'%PDF-');
 }
 await unit(superPage,1);await open(superPage,1,data.payments[1].kasir.id);const cards=superPage.locator('[data-payment-record]');await cards.nth(1).click();await cards.nth(3).click();await superPage.waitForFunction(()=>!document.querySelector('[data-payment-detail]').hasAttribute('aria-busy'));assert.ok((await superPage.locator('[data-payment-detail]').innerText()).includes('TRX-'+String(await cards.nth(3).getAttribute('data-id')).padStart(6,'0')));
 await superPage.locator('[data-payment-close]').click();assert.equal(await superPage.locator('[data-payment-detail-panel]').isVisible(),false);await cards.nth(2).click();assert.equal(await superPage.locator('[data-payment-detail-panel]').isVisible(),true);
 await superPage.goto(url('/pembayaran/lihat.php?per_page=10'));await superPage.getByRole('link',{name:'Halaman berikutnya',exact:true}).click();assert.ok(new URL(superPage.url()).searchParams.get('page')==='2');
 await superPage.goto(url('/pembayaran/lihat.php?search=NO_MATCH_HISTORY_TEST'));assert.equal(await superPage.locator('[data-payment-record]').count(),0);assert.ok((await superPage.locator('.ph-empty').first().innerText()).includes('Tidak ada transaksi'));
 const nojs=await login('kasir',1,{javaScriptEnabled:false});await open(nojs,1,data.payments[1].kasir.id);await nojs.locator('[data-payment-record]').nth(2).click({force:true});assert.ok((await nojs.locator('[data-payment-detail]').innerText()).includes('TRX-'+String(await nojs.locator('.ph-record.is-selected').getAttribute('data-id')).padStart(6,'0')));await nojs.context().close();
 assert.equal(nativeDialogs,0,'Native confirmation remains.');assert.deepEqual(errors,[]);console.log('OK: four scopes, active/deleted, desktop/tablet/mobile, light/dark, AJAX race/no-JS/pagination, modern confirmations.');
}finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
