const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
if(process.env.SPP_TEST_ALLOW_MUTATION!=='1'||!/^db_spp_audit_[a-z0-9_]+$/.test(process.env.SPP_DB_NAME||''))throw Error('Audit clone required.');
const base=process.env.SPP_TEST_BASE_URL||'http://127.0.0.1:8771';if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base))throw Error('Loopback required.');
const data=JSON.parse(fs.readFileSync(process.env.SPP_HISTORY_IDS_FILE,'utf8')),pending=JSON.parse(fs.readFileSync(process.env.SPP_AUTH_PENDING_FILE,'utf8'));
const password=fs.readFileSync(process.env.SPP_TEST_ADMIN_PASSWORD_FILE,'utf8').trim(),output=process.env.SPP_AUTH_OUTPUT;
const {chromium}=require(process.env.SPP_PLAYWRIGHT_CORE||'playwright-core');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];let native=0;
try{
 async function login(a){const page=await browser.newPage({viewport:{width:1600,height:1000}});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{native++;d.dismiss();});await page.goto(base+'/login.php');await page.locator('#username').fill(a.username);await page.locator('#password').fill(password);await Promise.all([page.waitForNavigation(),page.locator('#btn-login').click()]);return page;}
 const superPage=await login(data.super);await superPage.goto(base+'/pembayaran/lihat.php');await Promise.all([superPage.waitForNavigation(),superPage.locator('#sidebar-unit-select').selectOption('1')]);
 for(const view of ['active','deleted'])for(const width of [1600,768,390])for(const theme of ['light','dark']){
  await superPage.setViewportSize({width,height:1000});await superPage.goto(base+'/pembayaran/lihat.php?view='+view);await superPage.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert.equal(await superPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await superPage.screenshot({path:path.join(output,`final-history-${view}-${width}-${theme}.png`),fullPage:true});
 }
 for(const width of [1600,768,390])for(const theme of ['light','dark']){
  await superPage.setViewportSize({width,height:1000});await superPage.goto(base+'/otorisasi_transaksi.php?selected='+pending[1].request_id);await superPage.evaluate(t=>document.documentElement.dataset.theme=t,theme);
  const reject=superPage.locator('form[data-auth-confirm]').filter({has:superPage.locator('[name="action"][value="reject"]')});await reject.locator('button[type=submit]').click();assert.equal(await superPage.locator('.auth-confirm-dialog[open]').count(),0,'Invalid rejection opened confirmation.');
  const approve=superPage.getByRole('button',{name:'Setujui dan Terapkan',exact:true});await approve.click();await superPage.locator('.auth-confirm-dialog[open]').waitFor();assert.equal(await superPage.locator('.auth-confirm-dialog').getAttribute('data-danger'),'true');assert.ok((await superPage.locator('.auth-confirm-dialog').innerText()).includes('jurnal aktivitas tetap tersimpan'));
  for(let i=0;i<5;i++){await superPage.keyboard.press('Tab');assert.equal(await superPage.evaluate(()=>!!document.activeElement.closest('.auth-confirm-dialog')),true,'Focus escaped dialog.');}
  assert.equal(await superPage.evaluate(()=>{const r=document.querySelector('.auth-confirm-dialog').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&Math.abs(r.left+r.width/2-innerWidth/2)<2&&Math.abs(r.top+r.height/2-innerHeight/2)<2;}),true);await superPage.screenshot({path:path.join(output,`confirmation-delete-${width}-${theme}.png`)});await superPage.keyboard.press('Escape');await superPage.waitForTimeout(50);assert.equal(await approve.evaluate(e=>document.activeElement===e),true);
 }
 const cashier=await login(data.accounts[1].kasir),id=data.payments[1].kasir.id,other=data.payments[1].super_admin.id;
 await cashier.goto(base+'/pembayaran/lihat.php?per_page=50&search='+data.payments[1].kasir.nis+'&selected='+other);assert.equal(await cashier.locator('[data-payment-locked]').count(),1);assert.equal(await cashier.locator('[data-payment-detail] a[href^="edit.php"]').count(),0);assert.equal(await cashier.locator('[data-print-payment]').count(),0);await cashier.locator('.open-payment-activity').click();await cashier.locator('.payment-activity-event').first().waitFor();await cashier.locator('[data-close-activity]').click();await cashier.screenshot({path:path.join(output,'locked-cashier.png'),fullPage:true});
 let fail=true;await cashier.route('**/pembayaran/detail.php?*',route=>fail?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,message:'Uji gagal memuat detail'})}):route.continue());await cashier.locator('[data-payment-record][data-id="'+id+'"]').click();await cashier.getByRole('button',{name:'Coba kembali',exact:true}).waitFor();fail=false;await cashier.getByRole('button',{name:'Coba kembali',exact:true}).click();await cashier.locator('[data-print-payment]').waitFor();assert.ok((await cashier.locator('[data-payment-detail]').innerText()).includes('TRX-'+String(id).padStart(6,'0')));
 for(const [suffix,status] of [['id[]=1',400],['id=1&view=wrong',400],['id='+id+'&unit_id=2',404]])assert.equal((await cashier.request.get(base+'/pembayaran/detail.php?'+suffix)).status(),status);
 assert.equal((await cashier.request.post(base+'/pembayaran/detail.php',{form:{id:String(id)}})).status(),405);
 const guest=await browser.newContext();assert.equal((await guest.request.get(base+'/pembayaran/detail.php?id='+id)).status(),401);await guest.close();
 for(const u of [1,2,3]){const treasurer=await login(data.accounts[u].bendahara);const response=await treasurer.request.get(base+'/laporan/cetak_struk.php?id='+data.payments[u].bendahara.id);assert.equal(response.status(),200);assert.ok((await response.text()).includes('UJI RIWAYAT'));assert.equal((await treasurer.request.get(base+'/laporan/cetak_struk.php?id='+data.payments[u].kasir.id)).status(),403);await treasurer.context().close();}
 assert.deepEqual(errors,[]);assert.equal(native,0);console.log('OK final visuals, confirmation validation/focus/Escape, locked UI, activity access, detail retry/method/input/unit/session, treasurer receipts.');
}finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
