<?php
session_start();
if(!isset($_SESSION['admin_id'])){header('Location: ../login.php');exit;}
require_once '../koneksi.php';require_once '../includes/auth.php';require_once '../includes/spp_billing.php';
requireRole(['admin','bendahara','kasir']);
if(empty($_SESSION['csrf_titipan_spp']))$_SESSION['csrf_titipan_spp']=bin2hex(random_bytes(32));
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    requireRole(['admin']);if(!hash_equals($_SESSION['csrf_titipan_spp'],(string)($_POST['csrf_token']??'')))throw new RuntimeException('Token keamanan tidak valid.');
    $nis=trim((string)($_POST['no_induk']??''));$raw=str_replace(['.',','],['','.'],trim((string)($_POST['nominal']??'0')));$amount=is_numeric($raw)?(float)$raw:-1;$method=(string)($_POST['metode']??'Tunai');$note=mb_substr(trim((string)($_POST['keterangan']??'')),0,255);
    if($nis===''||$amount<=0)throw new RuntimeException('Pilih siswa dan isi nominal pengembalian.');if(!in_array($method,['Tunai','VA','Qris'],true))throw new RuntimeException('Metode pengembalian tidak valid.');
    $koneksi->begin_transaction();$balance=spp_deposit_balance($koneksi,$nis,true);if($amount>$balance+.001)throw new RuntimeException('Nominal melebihi saldo Titipan SPP Rp '.number_format($balance,0,',','.').'.');
    $kind='pengembalian';$date=date('Y-m-d H:i:s');$user=(string)$_SESSION['admin_id'];$stmt=$koneksi->prepare('INSERT INTO titipan_spp_mutasi(no_induk,jenis,nominal,tanggal,sistem_pembayaran,user_id,keterangan) VALUES(?,?,?,?,?,?,?)');$stmt->bind_param('ssdssss',$nis,$kind,$amount,$date,$method,$user,$note);$stmt->execute();$stmt->close();spp_write_audit($koneksi,null,$nis,'pengembalian_titipan',['saldo'=>$balance],['nominal'=>$amount,'saldo'=>$balance-$amount,'metode'=>$method],1);$koneksi->commit();$_SESSION['flash']=['type'=>'success','msg'=>'Pengembalian Titipan SPP berhasil dicatat sebagai kas keluar.'];
  }catch(Throwable $e){if($koneksi->errno===0||$koneksi->error===''){@$koneksi->rollback();}$_SESSION['flash']=['type'=>'error','msg'=>$e->getMessage()];}
  header('Location: titipan_spp.php');exit;
}
$flash=$_SESSION['flash']??null;unset($_SESSION['flash']);$q=mb_substr(trim((string)($_GET['q']??'')),0,100);$like='%'.$q.'%';
$stmt=$koneksi->prepare("SELECT s.NO_INDUK,s.NAMA,COALESCE(SUM(CASE WHEN m.jenis IN ('masuk','koreksi_masuk') THEN m.nominal ELSE -m.nominal END),0) saldo FROM siswa s LEFT JOIN titipan_spp_mutasi m ON m.no_induk=s.NO_INDUK WHERE s.NO_INDUK LIKE ? OR s.NAMA LIKE ? GROUP BY s.NO_INDUK,s.NAMA HAVING saldo>0.001 ORDER BY s.NAMA");$stmt->bind_param('ss',$like,$like);$stmt->execute();$balances=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();
$mutations=$koneksi->query("SELECT m.*,s.NAMA,COALESCE(a.nama,m.user_id) operator FROM titipan_spp_mutasi m JOIN siswa s ON s.NO_INDUK=m.no_induk LEFT JOIN admin a ON CAST(a.id AS CHAR)=m.user_id ORDER BY m.tanggal DESC,m.id DESC LIMIT 200")->fetch_all(MYSQLI_ASSOC);
function ts_e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Titipan SPP | SistemSPP</title><link rel="stylesheet" href="../assets/css/style.css?v=10.1"><script>(function(){document.documentElement.setAttribute('data-theme',localStorage.getItem('spp_theme')||'dark')})();</script></head><body><div class="layout"><?php include '../includes/sidebar.php';?><main class="main-content"><div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()">☰</button><div class="topbar-title"><h2>Titipan SPP</h2><span class="breadcrumb">Pembayaran / Titipan SPP</span></div><div class="clock-badge" id="liveClock">--:--:--</div></div>
<?php if($flash):?><div class="alert alert-<?=ts_e($flash['type'])?>" id="flash-msg"><?=ts_e($flash['msg'])?></div><?php endif;?>
<section class="main-card master-modern-shell"><div class="master-modern-hero"><div><span class="recap-class-overline">Buku Besar</span><h1>Saldo Titipan SPP</h1><p>Dana ini hanya dapat dialokasikan untuk tagihan SPP siswa yang sama.</p></div><div class="master-modern-stats"><div><span>Siswa Bersaldo</span><strong><?=count($balances)?></strong></div><div><span>Total Saldo</span><strong>Rp <?=number_format(array_sum(array_column($balances,'saldo')),0,',','.')?></strong></div></div></div></section>
<?php if(hasRole(['admin'])):?><section class="main-card master-modern-card"><div class="card-title">Pengembalian Titipan</div><p class="payment-auto-note">Pengembalian dicatat sebagai kas keluar dan tidak dapat dipindahkan ke siswa lain.</p><form method="post" class="fields-grid"><input type="hidden" name="csrf_token" value="<?=ts_e($_SESSION['csrf_titipan_spp'])?>"><div class="field-row"><label class="field-label">Siswa</label><select class="field-input field-select" name="no_induk" required><option value="">Pilih siswa</option><?php foreach($balances as $b):?><option value="<?=ts_e($b['NO_INDUK'])?>"><?=ts_e($b['NAMA'])?> · Rp <?=number_format($b['saldo'],0,',','.')?></option><?php endforeach;?></select></div><div class="field-row"><label class="field-label">Nominal</label><input class="field-input rupiah-input" name="nominal" inputmode="numeric" required></div><div class="field-row"><label class="field-label">Metode</label><select class="field-input field-select" name="metode"><option>Tunai</option><option>VA</option><option>Qris</option></select></div><div class="field-row"><label class="field-label">Keterangan</label><input class="field-input" name="keterangan" maxlength="255" required></div><div class="action-bar full-span"><button class="btn btn-warning" type="submit" onclick="return confirm('Catat pengembalian Titipan SPP ini?')">Catat Pengembalian</button></div></form></section><?php endif;?>
<section class="main-card master-modern-card"><div class="card-title-row"><div class="card-title">200 Mutasi Terbaru</div><a class="btn btn-ghost" href="../laporan/template.php?template=titipan-spp">Buka Laporan Lengkap</a></div><div class="table-container"><table class="payment-table responsive-table"><thead><tr><th>Tanggal</th><th>Siswa</th><th>Jenis</th><th>Masuk</th><th>Keluar</th><th>Operator</th><th>Keterangan</th></tr></thead><tbody><?php if(!$mutations):?><tr><td colspan="7">Belum ada mutasi Titipan SPP.</td></tr><?php endif;foreach($mutations as $m):$incoming=in_array($m['jenis'],['masuk','koreksi_masuk'],true);?><tr><td><?=ts_e(date('d/m/Y H:i',strtotime($m['tanggal'])))?></td><td><strong><?=ts_e($m['NAMA'])?></strong><small class="du-history-nis"><?=ts_e($m['no_induk'])?></small></td><td><?=ts_e(ucwords(str_replace('_',' ',$m['jenis'])))?></td><td class="nominal"><?=$incoming?'Rp '.number_format($m['nominal'],0,',','.'):'-'?></td><td class="nominal"><?=!$incoming?'Rp '.number_format($m['nominal'],0,',','.'):'-'?></td><td><?=ts_e($m['operator'])?></td><td><?=ts_e($m['keterangan'])?></td></tr><?php endforeach;?></tbody></table></div></section></main></div><script src="../assets/js/app.js?v=10.1"></script><script>document.querySelectorAll('.rupiah-input').forEach(i=>i.addEventListener('input',()=>{const n=i.value.replace(/\D/g,'');i.value=n?Number(n).toLocaleString('id-ID'):''}));autoHideFlash();</script></body></html>
