-- Encoded internal SQL definition; run only through sql/run_legacy_sql.php.
B64:U0lHTkFMIFNRTFNUQVRFICc0NTAwMCcgU0VUIE1FU1NBR0VfVEVYVD0nRGVmaW5pc2kgbGFtYSB0aWRhayBzZXN1YWkgc2tlbWEgUFNCL3BvdG9uZ2FuIG5vbWluYWw7IGd1bmFrYW4gbWlncmFzaSBDTEkgdGVyYmFydSc7Cg==
