<?php
require_once '../includes/security.php';
security_bootstrap_session();
require_once '../koneksi.php'; require_once '../includes/auth.php'; require_once '../includes/reports.php';
requireRole(['admin','bendahara','kasir']);
$registry=report_registry();$template=(string)report_input_scalar($_GET, 'template');if(!isset($registry[$template])){http_response_code(404);exit('Template tidak ditemukan.');}
$format=(string)report_input_scalar($_GET, 'format', 'print');if(!in_array($format,['print','pdf','excel'],true))$format='print';
$filters=report_filters($koneksi,$_GET);$defaults=report_template_defaults($template,$_GET,$filters,report_classes($koneksi));$filters=$defaults['filters'];$missingRombel=$defaults['missing_rombel'];
try{$report=report_build($koneksi,$template,$filters);}catch(LengthException $error){http_response_code(413);exit(report_e($error->getMessage()));}catch(Throwable $error){http_response_code(500);exit(report_e(security_exception_message($error,'Laporan tidak dapat diekspor.','report-export')));}
if($missingRombel){$report['rows']=[];$report['details']=[];}
if(count($report['rows'])>10000){http_response_code(413);exit('Ekspor dibatasi maksimal 10.000 baris. Persempit filter laporan.');}
$generated=date('d-m-Y H:i:s');$operator=(string)($_SESSION['admin_nama']??$_SESSION['admin_username']??'Pengguna');
function export_cell($value,string $type,string $key=''):string{global $format;if($type==='money')return report_e(report_money($value));if($type==='html'&&is_array($value))$value=($value['text']??'').(($value['sub']??'')!==''?' · '.$value['sub']:'');if($format==='excel'){$value=report_spreadsheet_text($value);if(in_array($key,['nis','nomor'],true)&&!str_starts_with((string)$value,"'"))$value="'".$value;}return report_e($value);}
$logoPath=realpath(__DIR__.'/../assets/img/school-logo.png');
// Dompdf membutuhkan GD untuk PNG. Print/Excel tetap memakai logo; PDF memberi
// fallback teks sampai ekstensi GD XAMPP diaktifkan dan Apache dimulai ulang.
$canRenderLogo=$format!=='pdf'||extension_loaded('gd');
$logoData=$logoPath&&$canRenderLogo?'data:image/png;base64,'.base64_encode((string)file_get_contents($logoPath)):'';
ob_start(); ?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><title><?= export_cell($report['title'],'text','title') ?></title><style>
@page{margin:12mm;size:<?= $registry[$template]['orientation']==='landscape'?'A4 landscape':'A4 portrait' ?>}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#17231d;font-size:9px;margin:0}.toolbar{padding:10px;background:#eef7f2;margin-bottom:12px}.toolbar button{padding:8px 14px;border:0;background:#108952;color:#fff;border-radius:6px;cursor:pointer}.kop{width:100%;border-bottom:3px double #15543c;padding-bottom:8px;margin-bottom:12px}.kop td{border:0}.kop img{width:58px;height:58px;object-fit:contain}.kop h1{font-size:16px;margin:0;text-align:center}.kop p{text-align:center;margin:3px 0}.title{text-align:center;margin:10px 0 12px}.title h2{font-size:14px;margin:0 0 3px}.meta{width:100%;margin-bottom:8px}.meta td{border:0;padding:2px}table.data{border-collapse:collapse;width:100%}.data th,.data td{border:1px solid #9bb9aa;padding:4px;vertical-align:top}.data th{background:#12503a;color:white;text-transform:uppercase;font-size:8px}.data tr:nth-child(even){background:#f4f8f6}.money{text-align:right;white-space:nowrap}.footer{position:fixed;bottom:-7mm;left:0;right:0;border-top:1px solid #aaa;padding-top:3px;color:#666;font-size:7px}.footer:after{content:" · Halaman " counter(page)}.signatures{width:100%;margin-top:24px}.signatures td{border:0;text-align:center;width:50%;height:70px;vertical-align:top}.negative{color:#b42318;font-weight:bold}@media print{.toolbar{display:none}}
</style></head><body><?php if($format==='print'): ?><div class="toolbar"><button onclick="window.print()">Cetak Laporan</button></div><?php endif; ?>
<table class="kop"><tr><td style="width:70px"><?php if($logoData): ?><img src="<?= $logoData ?>"><?php endif; ?></td><td><h1>SEKOLAH DASAR AL-QUR'AN (SDA) MUTIARA HIKMAH</h1><p>Perum Bekasi Griya Asri II, Tambun Selatan · Telp. 021-88363466</p></td><td style="width:70px"></td></tr></table>
<div class="title"><h2><?= export_cell(strtoupper($report['title']),'text','title') ?></h2><div><?= export_cell($report['subtitle'],'text','subtitle') ?></div></div><table class="meta"><tr><td>Dibuat: <?= export_cell($generated,'text','generated') ?></td><td style="text-align:right">Petugas: <?= export_cell($operator,'text','operator') ?></td></tr></table>
<table class="data"><thead><tr><th>No</th><?php foreach($report['columns'] as $column): ?><th><?= report_e($column[1]) ?></th><?php endforeach; ?></tr></thead><tbody><?php if(!$report['rows']): ?><tr><td colspan="<?= count($report['columns'])+1 ?>" style="text-align:center">Tidak ada data pada filter terpilih.</td></tr><?php else: foreach($report['rows'] as $index=>$row): ?><tr><td><?= $index+1 ?></td><?php foreach($report['columns'] as $column): $type=$column[2]??'text';$key=$column[0];$value=$row[$key]??''; ?><td class="<?= $type==='money'?'money':'' ?> <?= is_numeric($value)&&(float)$value<0?'negative':'' ?>"><?= export_cell($value,$type,$key) ?></td><?php endforeach; ?></tr><?php endforeach; endif; ?></tbody></table>
<?php if($template==='setoran'&&!empty($report['details'])): ?><h3>Rincian Penerimaan Pembayaran</h3><table class="data"><thead><tr><th>Waktu</th><th>No. Transaksi</th><th>Siswa</th><th>Komponen</th><th>Metode</th><th>Nominal</th></tr></thead><tbody><?php foreach($report['details'] as $detail): ?><tr><td><?= export_cell($detail['tanggal'],'text','tanggal') ?></td><td><?= export_cell($detail['nomor'],'text','nomor') ?></td><td><?= export_cell($detail['nis'].' · '.$detail['nama'],'text','nis') ?></td><td><?= export_cell($detail['komponen'],'text','komponen') ?></td><td><?= export_cell($detail['metode'],'text','metode') ?></td><td class="money"><?= report_money($detail['nominal']) ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?>
<?php if($template==='setoran'): ?><table class="signatures"><tr><td>Kasir/Petugas,<br><br><br><br>(________________________)</td><td>Bagian Keuangan,<br><br><br><br>(________________________)</td></tr></table><?php endif; ?><div class="footer">SistemSPP · Data laporan bersifat live dan mengikuti koreksi transaksi sampai saat laporan dibuat.</div></body></html>
<?php $html=ob_get_clean();$safeName=preg_replace('/[^a-z0-9_-]+/i','-',strtolower($template)).'-'.date('Ymd-His');
if($format==='excel'){header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$safeName.'.xls"');echo "\xEF\xBB\xBF".$html;exit;}
if($format==='pdf'){require_once '../vendor/autoload.php';$options=new \Dompdf\Options();$options->set('isRemoteEnabled',false);$options->set('isHtml5ParserEnabled',true);$dompdf=new \Dompdf\Dompdf($options);$dompdf->loadHtml($html,'UTF-8');$dompdf->setPaper('A4',$registry[$template]['orientation']);$dompdf->render();$dompdf->stream($safeName.'.pdf',['Attachment'=>true]);exit;}
echo $html;
