<?php
session_start();
require_once __DIR__.'/../koneksi.php';
require_once __DIR__.'/../includes/auth.php';
require_once __DIR__.'/../includes/parent_letter_drafts.php';
require_once __DIR__.'/../includes/account_letter_ui.php';
requireRole(['admin','bendahara','kasir']);
header('Cache-Control: no-store, private');
try {
    if(isset($_GET['draft'])&&!is_string($_GET['draft']))throw new InvalidArgumentException('Draf tidak valid.');
    $token=$_GET['draft']??'';
    if($token===''){$token=parent_letter_draft_create(parent_letter_collect($koneksi,$_GET));header('Location: surat_orang_tua_susun.php?draft='.$token);exit;}
    $draft=parent_letter_draft_read($token);
}catch(Throwable $e){http_response_code(400);echo '<!doctype html><html lang="id"><meta charset="utf-8"><title>Surat tidak tersedia</title><p>'.report_e($e->getMessage()).'</p><a href="surat_orang_tua.php">Kembali ke daftar surat</a></html>';exit;}
if(empty($_SESSION['csrf_parent_letter']))$_SESSION['csrf_parent_letter']=bin2hex(random_bytes(32));
$preview=($_GET['preview']??'')==='1';$pdfUrl='surat_orang_tua_pdf.php?draft='.$token;
$recipients=[];foreach($draft['students'] as $student)$recipients[]=['key'=>unit_student_key($student),'name'=>$student['nama'],'nis'=>$student['nis'],'diknas'=>$student['nis_diknas']??'','class'=>$student['kelas'],'unit'=>unit_label((int)$student['unit_id'])];
?>
<!doctype html><html lang="id" data-palette="<?= unit_palette_for_view() ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $preview?'Pratinjau':'Susun' ?> Surat Orang Tua | SistemSPP</title>
<link rel="icon" href="../assets/img/favicon.png"><link rel="stylesheet" href="../assets/css/style.css?v=<?= filemtime(__DIR__.'/../assets/css/style.css') ?>"><link rel="stylesheet" href="../assets/css/parent_letter_workspace.css?v=<?= filemtime(__DIR__.'/../assets/css/parent_letter_workspace.css') ?>">
<link rel="stylesheet" href="../assets/css/workspace_readability.css?v=<?= filemtime(__DIR__.'/../assets/css/workspace_readability.css') ?>">
<script>document.documentElement.dataset.theme=localStorage.getItem('spp_theme')||'light';</script></head><body class="parent-letter-workspace" data-readable-workspace="parent"><div class="layout"><?php include __DIR__.'/../includes/sidebar.php'; ?><main class="main-content">
<div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()" aria-label="Buka menu"><?= account_letter_icon('menu') ?></button><div class="topbar-title"><h2><?= $preview?'Pratinjau':'Susun' ?> Surat Orang Tua</h2><span class="breadcrumb">Surat Laporan / Orang Tua</span></div><div id="liveClock" class="clock-badge"></div></div>
<div class="parent-compose"><section class="main-card parent-letter-card"><header class="parent-compose-header"><div><span class="parent-overline">SURAT KE ORANG TUA</span><h1><?= $preview?'Periksa surat sebelum mencetak':'Susun pesan untuk setiap siswa' ?></h1><p><?= count($recipients) ?> penerima · Tunggakan sampai <?= report_e(report_date_label($draft['today'])) ?><?= $preview?' · Draf berlaku dua jam sejak dibuat.':'' ?></p></div><span class="parent-header-art"><?= account_letter_icon('document') ?><span><?= account_letter_icon($preview?'search':'edit') ?></span></span></header>
<?php if($preview): ?>
<div class="parent-compose-actions parent-preview-actions"><a class="btn btn-ghost" href="?draft=<?= report_e($token) ?>"><?= account_letter_icon('left') ?>Kembali ke penyusunan</a><button class="btn btn-primary" type="button" id="parent-print"><?= account_letter_icon('print') ?>Cetak</button><a class="btn btn-ghost" href="<?= report_e($pdfUrl.'&download=1') ?>"><?= account_letter_icon('download') ?>Unduh PDF</a><a class="btn btn-ghost parent-open-pdf" href="<?= report_e($pdfUrl) ?>" target="_blank" rel="noopener" title="Buka PDF di tab baru" aria-label="Buka PDF di tab baru"><?= account_letter_icon('external') ?>Buka PDF</a><span class="parent-compose-status">Surat memakai data saat draf dibuat.</span></div>
<div class="parent-preview-viewer"><iframe title="Pratinjau PDF surat orang tua" class="parent-preview-frame" id="parent-pdf-frame" src="<?= report_e($pdfUrl.'#toolbar=1&navpanes=1&view=FitH') ?>"></iframe></div>
<div class="parent-preview-note"><?= account_letter_icon('info') ?><span><strong>Catatan</strong>Ini adalah pratinjau surat. Pastikan seluruh data dan pesan sudah sesuai sebelum dicetak atau diunduh.</span></div>
<script>
(() => {const frame=document.getElementById('parent-pdf-frame'),button=document.getElementById('parent-print');button.disabled=true;frame.addEventListener('load',()=>{button.disabled=false;});button.addEventListener('click',()=>{try{frame.contentWindow.focus();frame.contentWindow.print();}catch(error){window.open(<?= json_encode($pdfUrl) ?>,'_blank','noopener');}});})();
</script>
<?php else: ?>
<div class="parent-compose-layout">
<aside class="parent-recipients"><h2>Daftar Penerima</h2><label class="parent-search"><?= account_letter_icon('search') ?><input class="field-input" id="recipient-search" placeholder="Cari nama, NIS, atau kelas..." aria-label="Cari penerima"></label><div class="parent-recipient-list">
<?php foreach($recipients as $recipient): $key=$recipient['key']; ?><button type="button" class="parent-recipient" data-key="<?= report_e($key) ?>" aria-pressed="false"><span class="parent-recipient-avatar"><?= account_letter_icon('user') ?></span><span><strong><?= report_e($recipient['name']) ?></strong><small><?= report_e($recipient['unit'].' · '.$recipient['nis'].' · '.$recipient['class']) ?></small><small data-message-status><?= parent_letter_message_text($draft['messages'][$key]??'')!==''?'Pesan tambahan terisi':'Tanpa pesan tambahan' ?></small></span></button><?php endforeach; ?>
</div><p class="parent-recipient-count" id="parent-recipient-count">Menampilkan <?= count($recipients) ?> dari <?= count($recipients) ?> penerima</p></aside>
<section class="parent-editor"><h2>Pesan untuk Orang Tua</h2>
<div class="parent-rich-editor"><div class="parent-editor-toolbar" role="toolbar" aria-label="Format pesan"><button type="button" data-format="formatBlock" data-value="p" title="Paragraf">Paragraf</button><button type="button" data-format="bold" aria-label="Tebal" aria-pressed="false"><strong>B</strong></button><button type="button" data-format="italic" aria-label="Miring" aria-pressed="false"><em>I</em></button><button type="button" data-format="underline" aria-label="Garis bawah" aria-pressed="false"><u>U</u></button><button type="button" data-format="insertUnorderedList" aria-label="Daftar berpoin" aria-pressed="false">• ≡</button><button type="button" data-format="insertOrderedList" aria-label="Daftar bernomor" aria-pressed="false">1. ≡</button></div><div id="parent-message" class="parent-message" contenteditable="true" role="textbox" aria-multiline="true" aria-label="Pesan tambahan untuk orang tua" data-placeholder="Tulis pesan..."></div></div>
<div class="parent-editor-footer"><span id="parent-message-count" class="parent-compose-status" aria-live="polite">0 / 2.000 karakter</span></div><div class="parent-copy-action"><div><strong>Gunakan pesan yang sama</strong></div><button type="button" class="parent-copy-button" id="parent-copy"><?= account_letter_icon('copy') ?><span>Terapkan ke Penerima Lain</span><?= account_letter_icon('right') ?></button></div></section>
<aside class="parent-summary"><h2>Ringkasan Penerima</h2><div class="parent-summary-card"><span class="parent-summary-avatar"><?= account_letter_icon('user') ?></span><h3 id="recipient-name"></h3><dl><dt>NIS</dt><dd id="summary-nis"></dd><dt>NIS Diknas</dt><dd id="summary-diknas"></dd><dt>Kelas/Rombel</dt><dd id="summary-class"></dd><dt>Unit</dt><dd id="summary-unit"></dd></dl><p id="recipient-identity" hidden></p></div></aside>
</div>
<div class="parent-compose-actions"><a class="btn btn-ghost" href="surat_orang_tua.php"><?= account_letter_icon('left') ?>Kembali ke daftar</a><button type="button" class="btn btn-ghost" id="parent-save"><?= account_letter_icon('save') ?>Simpan Draf</button><button type="button" class="btn btn-primary" id="parent-preview"><?= account_letter_icon('document') ?>Pratinjau Surat<?= account_letter_icon('right') ?></button><span id="parent-save-status" class="parent-compose-status" role="status" aria-live="polite"></span></div>
<dialog id="parent-copy-dialog" class="parent-copy-dialog" aria-labelledby="parent-copy-title"><header><span class="parent-dialog-icon"><?= account_letter_icon('copy') ?></span><div><h2 id="parent-copy-title">Terapkan pesan ke penerima lain</h2></div><button type="button" data-copy-close aria-label="Tutup dialog"><?= account_letter_icon('close') ?></button></header><div class="parent-copy-content"><div class="parent-copy-source"><small>Sumber pesan</small><strong id="copy-source-name"></strong></div><label class="parent-search"><?= account_letter_icon('search') ?><input id="copy-recipient-search" class="field-input" placeholder="Cari penerima..." aria-label="Cari target pesan"></label><label class="parent-copy-all"><input type="checkbox" id="copy-select-all">Pilih Semua <span id="copy-total"></span></label><div id="copy-recipient-list" class="parent-copy-list"></div><p class="parent-copy-help">Pesan penerima yang dipilih akan diganti.</p><p id="copy-result" class="parent-compose-status" role="status"></p></div><footer><span id="copy-selected-count"></span><button type="button" class="btn btn-ghost" data-copy-close>Batal</button><button type="button" class="btn btn-primary" id="copy-apply">Terapkan Pesan</button></footer></dialog>
<script id="parent-draft-data" type="application/json"><?= json_encode(['token'=>$token,'csrf'=>$_SESSION['csrf_parent_letter'],'messages'=>$draft['messages'],'recipients'=>$recipients],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE) ?></script><script src="../assets/js/parent_letter_editor.js?v=<?= filemtime(__DIR__.'/../assets/js/parent_letter_editor.js') ?>"></script>
<?php endif; ?></section></div></main></div><script src="../assets/js/date_format.js"></script><script src="../assets/js/app.js"></script></body></html>
