<?php
session_start();
require_once __DIR__.'/../koneksi.php';
require_once __DIR__.'/../includes/auth.php';
require_once __DIR__.'/../includes/reports.php';
requireRole(['admin','bendahara','kasir']);

$filters=report_filters($koneksi,$_GET);
$filters['status']='';unset($filters['_multi']['status']);filter_output_start();
$today=report_letter_today();
$students=report_student_debt_groups($koneksi,$filters,'',[],$today);
$allFilters=$filters;$allFilters['kelas']='';unset($allFilters['_multi']['kelas']);$allFilters['q']='';
$allStudents=report_student_debt_groups($koneksi,$allFilters,'',[],$today);
$classStudents=($filters['kelas']!==''||!filter_is_all($filters['_multi']['kelas']??['*']))?report_student_debt_groups($koneksi,$filters,'',[],$today):[];
$classes=report_classes($koneksi);
$total=array_sum(array_map(static fn($student)=>(float)$student['total_tunggakan'],$students));
?>
<!doctype html><html lang="id" data-palette="<?= unit_palette_for_view() ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cetak Surat ke Orang Tua | SistemSPP</title><link rel="icon" href="../assets/img/favicon.png?v=2"><link rel="stylesheet" href="../assets/css/style.css?v=unitpalette6&amp;mtime=<?= filemtime(__DIR__ . '/../assets/css/style.css') ?>"><link rel="stylesheet" href="../assets/css/date_controls.css?v=unitpalette6&amp;mtime=<?= filemtime(__DIR__ . '/../assets/css/date_controls.css') ?>"><script>(function(){document.documentElement.setAttribute('data-theme',localStorage.getItem('spp_theme')||'light')})();</script></head><body>
<div class="bg-orbs"><div class="orb orb-1"></div><div class="orb orb-2"></div><div class="orb orb-3"></div></div>
<div class="layout"><?php include __DIR__.'/../includes/sidebar.php'; ?><main class="main-content">
<div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()" aria-label="Buka navigasi">☰</button><div class="topbar-title"><h2>Cetak Surat ke Orang Tua</h2><span class="breadcrumb"><a href="surat_laporan.php">Surat Laporan</a> / Orang Tua</span></div><div class="clock-badge" id="liveClock">--:--:--</div></div>
<div class="letter-list-shell">
<a class="letter-back-link" href="surat_laporan.php">&larr; Kembali ke pilihan surat</a>
<section class="main-card letter-list-card"><div class="letter-list-head"><div class="letter-list-heading"><span class="recap-class-overline">SURAT KE ORANG TUA</span><h1>Pilih siswa yang akan dikirimi surat</h1><p>Menampilkan tunggakan sampai <?= report_e(report_date_label($today)) ?>. Siswa yang sudah lunas tidak masuk daftar.</p></div><div class="letter-total"><span>Siswa dengan tunggakan</span><strong><?= number_format(count($students)) ?></strong><span>Total <?= report_e(report_money($total)) ?></span></div></div>
<form method="get" class="letter-filters"><div class="field-row"><label class="field-label" for="letter-class">Kelas/Rombel</label><select class="field-input field-select" id="letter-class" name="kelas" data-filter-multiple><option value="">Semua Rombel</option><?php foreach(range(...unit_level_bounds()) as $level): ?><option value="tingkat:<?= $level ?>" <?= $filters['kelas']==='tingkat:'.$level?'selected':'' ?>>Semua Kelas <?= $level ?></option><?php endforeach; ?><?php foreach($classes as $class): ?><option value="rombel:<?= (int)$class['id'] ?>" <?= $filters['kelas']==='rombel:'.(int)$class['id']?'selected':'' ?>><?= report_e($class['label']) ?></option><?php endforeach; ?></select></div><div class="field-row"><label class="field-label" for="letter-status">Status Siswa</label><select class="field-input field-select" id="letter-status" name="siswa_status" data-filter-multiple><?php foreach(['active'=>'Aktif','archived'=>'Arsip/Lulus','all'=>'Semua'] as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['siswa_status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><div class="field-row letter-search"><label class="field-label" for="letter-q">Cari siswa</label><input class="field-input" id="letter-q" name="q" value="<?= report_e($filters['q']) ?>" placeholder="Nama, NIS, atau NIS Diknas"></div><button class="btn btn-primary" type="submit">Tampilkan siswa</button></form>
<div class="letter-actions" aria-label="Pilihan cetak surat">
  <div class="letter-action-copy"><strong><?= number_format(count($students)) ?> surat sesuai filter</strong><span>Pilih siswa di tabel atau cetak menurut rombel. Sesuaikan pesan tiap siswa sebelum pratinjau. Setiap siswa mulai di lembar baru.</span></div>
  <div class="letter-action-buttons">
    <button type="button" class="btn btn-ghost" id="print-selected" disabled>Cetak Dipilih (0)</button>
    <?php if(($filters['kelas']===''&&filter_is_all($filters['_multi']['kelas']??['*']))): ?>
      <button type="button" class="btn btn-ghost" disabled title="Pilih kelas atau rombel dahulu">Cetak Kelas/Rombel</button>
    <?php else: ?>
      <a class="btn btn-ghost <?= !$classStudents?'is-disabled':'' ?>" target="_blank" rel="noopener" <?= $classStudents?'':'aria-disabled="true" tabindex="-1"' ?> href="surat_orang_tua_susun.php?<?= filter_build_query(['mode'=>'class','kelas'=>$filters['kelas'],'q'=>$filters['q'],'siswa_status'=>$filters['siswa_status']]) ?>">Cetak Kelas/Rombel (<?= count($classStudents) ?>)</a>
    <?php endif; ?>
    <a class="btn btn-primary <?= !$allStudents?'is-disabled':'' ?>" target="_blank" rel="noopener" <?= $allStudents?'':'aria-disabled="true" tabindex="-1"' ?> href="surat_orang_tua_susun.php?<?= filter_build_query(['mode'=>'all','siswa_status'=>$filters['siswa_status']]) ?>">Cetak Semua Rombel (<?= count($allStudents) ?>)</a>
  </div>
</div>
<p class="letter-table-hint">Geser tabel ke samping untuk melihat sisa tagihan dan tombol cetak.</p>
<div class="table-container letter-table-wrap" role="region" tabindex="0" aria-label="Daftar siswa dengan tunggakan, dapat digeser ke samping"><table class="data-table letter-student-table"><thead><tr><th class="letter-select-cell"><label class="letter-select-all"><input type="checkbox" id="select-page" aria-label="Pilih semua siswa pada halaman ini"><span>Pilih</span></label></th><th>Siswa</th><th>Kelas</th><th>Tagihan</th><th>Sisa Tagihan</th><th class="letter-action-cell">Surat</th></tr></thead><tbody><?php if(!$students): ?><tr><td colspan="6" class="letter-empty">Tidak ada siswa dengan tunggakan pada filter ini.</td></tr><?php else: foreach($students as $student): ?><tr class="letter-student-row"><td class="letter-select-cell"><input type="checkbox" class="letter-select" value="<?= report_e(unit_student_key($student)) ?>" aria-label="Pilih <?= report_e($student['nama']) ?>"></td><td class="letter-student-name"><strong><?= unit_record_badge($student) ?><?= report_e($student['nama']) ?></strong><small>NIS <?= report_e($student['nis']) ?><?= ($student['nis_diknas']??'')!==''?' · Diknas '.report_e($student['nis_diknas']):'' ?></small></td><td><?= report_e($student['kelas']) ?></td><td><?= count($student['items']) ?> tagihan</td><td class="money"><?= report_e(report_money($student['total_tunggakan'])) ?></td><td class="letter-action-cell"><a class="btn btn-ghost btn-sm" target="_blank" rel="noopener" aria-label="Cetak surat untuk <?= report_e($student['nama']) ?>" href="surat_orang_tua_susun.php?<?= filter_build_query(['mode'=>'single','student_key'=>unit_student_key($student),'siswa_status'=>$filters['siswa_status']]) ?>">Cetak Surat</a></td></tr><?php endforeach; endif; ?></tbody></table></div>
<div class="letter-pages"><span id="page-info"></span><div><button type="button" class="btn btn-ghost btn-sm" id="page-prev">Sebelumnya</button><button type="button" class="btn btn-ghost btn-sm" id="page-next">Berikutnya</button></div></div>
</section></div></main></div><script src="../assets/js/date_format.js"></script>
  <script src="../assets/js/app.js"></script><script>
(()=>{const rows=[...document.querySelectorAll('.letter-student-row')],boxes=[...document.querySelectorAll('.letter-select')],selected=document.getElementById('print-selected'),all=document.getElementById('select-page'),info=document.getElementById('page-info'),prev=document.getElementById('page-prev'),next=document.getElementById('page-next');let page=1;const size=25,max=Math.max(1,Math.ceil(rows.length/size));function draw(){rows.forEach((row,i)=>row.hidden=Math.floor(i/size)+1!==page);info.textContent=rows.length?`${(page-1)*size+1}–${Math.min(page*size,rows.length)} dari ${rows.length} siswa`:'0 siswa';prev.disabled=page===1;next.disabled=page===max;all.checked=false;all.indeterminate=false;const visible=boxes.filter((_,i)=>Math.floor(i/size)+1===page);if(visible.length){all.checked=visible.every(box=>box.checked);all.indeterminate=!all.checked&&visible.some(box=>box.checked)}const count=boxes.filter(box=>box.checked).length;selected.textContent=`Cetak Dipilih (${count})`;selected.disabled=count===0}all.addEventListener('change',()=>{boxes.forEach((box,i)=>{if(Math.floor(i/size)+1===page)box.checked=all.checked});draw()});boxes.forEach(box=>box.addEventListener('change',draw));prev.addEventListener('click',()=>{page--;draw()});next.addEventListener('click',()=>{page++;draw()});selected.addEventListener('click',()=>{const nis=boxes.filter(box=>box.checked).map(box=>box.value);if(!nis.length)return;const url=new URL('surat_orang_tua_susun.php',location.href);url.searchParams.set('mode','selected');url.searchParams.set('students',nis.join(','));for(const value of <?= json_encode($GLOBALS['spp_filter_choices']['siswa_status']['values']) ?>)url.searchParams.append('siswa_status[]',value);window.open(url.toString(),'_blank','noopener')});draw()})();
</script></body></html>
