<?php
session_start();
require_once '../koneksi.php'; require_once '../includes/auth.php'; require_once '../includes/reports.php'; require_once '../includes/pagination.php';
requireRole(['admin','bendahara','kasir']);
$registry=report_registry(); $template=(string)($_GET['template']??'');
if(!isset($registry[$template])){ header('Location: global.php'); exit; }
$filters=report_filters($koneksi,$_GET);
if($template==='riwayat-tagihan'&&!isset($_GET['siswa_status'])) $filters['siswa_status']='all';
if(!isset($_GET['kategori'])&&$template==='penerimaan') $filters['kategori']='semua';
$perItemUsesMonthly=$template==='per-item'&&report_item_is_monthly_category($filters['kategori']);
$perItemUsesAnnual=$template==='per-item'&&array_key_exists($filters['kategori'],annual_fee_components());
$templateFilterClass='report-filter-'.preg_replace('/[^a-z0-9_-]+/i','-',$template);
$classes=report_classes($koneksi);$classLevels=['1','2','3','4','5','6'];$missingRombel=false;
try { $report=report_build($koneksi,$template,$filters); }
catch(Throwable $e){ $report=['title'=>$registry[$template]['label'],'subtitle'=>'Gagal memuat laporan','columns'=>[],'rows'=>[],'error'=>$e->getMessage()]; }
if($missingRombel){$report['rows']=[];$report['error']='Belum ada rombel nyata. Admin perlu membuat Master Kelas/Rombel lalu memindahkan siswa dari placeholder Belum Ditentukan.';}
$pagination=report_paginate($report['rows'],$filters,false);
$years=report_years($koneksi); $operatorOptions=report_operator_options($koneksi); $operatorFilterLabel=report_operator_filter_label(); $categories=report_categories($koneksi); $billingCategories=$template==='riwayat-tagihan'?report_billing_categories($koneksi):[]; $query=array_merge($_GET,$filters,['template'=>$template]);
$moneyTotals=report_money_totals($report,$template);$useGlobalIdentitySticky=in_array($template,['penerimaan','spp-tahunan','per-item'],true);
$studentOptionWhere=in_array($template,['saldo-tabungan','riwayat-tagihan'],true)&&$filters['siswa_status']!=='active'?'':' WHERE s.is_active=1';
$studentOptions=$koneksi->query("SELECT s.NO_INDUK,s.NO_induk_diknas,s.NAMA,s.KELAS,s.master_kelas_id,mk.tingkat AS master_tingkat,mk.kode_rombel,mk.is_placeholder FROM siswa s LEFT JOIN master_kelas mk ON mk.id=s.master_kelas_id$studentOptionWhere ORDER BY s.NAMA ASC")->fetch_all(MYSQLI_ASSOC);
$studentSearchDisplay=$filters['q'];foreach($studentOptions as $studentOption){if($filters['q']!==''&&($filters['q']===$studentOption['NO_INDUK']||$filters['q']===(string)($studentOption['NO_induk_diknas']??''))){$studentSearchDisplay=$studentOption['NAMA'];break;}}
$summaryCards=report_summaries($report['rows']);$visibleRows=count($pagination['rows']);$totalRows=count($report['rows']);$exportQuery=$query;$exportQuery['page']=1;$firstShown=$totalRows>0?(($pagination['page']-1)*$pagination['per_page'])+1:0;$lastShown=$totalRows>0?min($totalRows,$pagination['page']*$pagination['per_page']):0;$resultRangeLabel=$totalRows<=0?'0 baris':($visibleRows===$totalRows?'Semua '.number_format($totalRows).' baris':number_format($firstShown).' s.d. '.number_format($lastShown).' dari '.number_format($totalRows).' baris');
$detailFilters=$filters;$detailFilters['page']=max(1,(int)($_GET['detail_page']??1));$detailPagination=$template==='setoran'?report_paginate($report['details']??[],$detailFilters,false):null;
function template_url(array $changes=[]):string { global $query; return 'template.php?'.http_build_query(array_merge($query,$changes)); }
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title><?= report_e($report['title']) ?> | SistemSPP</title><link rel="icon" href="../assets/img/favicon.png?v=2"><link rel="stylesheet" href="../assets/css/style.css?v=8.7"><script>(function(){document.documentElement.setAttribute('data-theme',localStorage.getItem('spp_theme')||'dark')})();</script></head><body>
<div class="bg-orbs"><div class="orb orb-1"></div><div class="orb orb-2"></div><div class="orb orb-3"></div></div><div class="layout"><?php include '../includes/sidebar.php'; ?><main class="main-content">
<div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()" aria-label="Buka navigasi"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button><div class="topbar-title"><h2><?= report_e($report['title']) ?></h2><span class="breadcrumb"><a href="global.php">Laporan Global</a> / <?= report_e($registry[$template]['label']) ?></span></div><div class="clock-badge" id="liveClock">--:--:--</div></div>
<section class="main-card class-recap-card recap-report-shell report-template-shell report-table-<?= report_e($templateFilterClass) ?>">
<?php if(in_array($template,['saldo-tabungan','riwayat-tagihan'],true)): ?><script>
document.addEventListener('DOMContentLoaded',function(){
  const form=document.querySelector('.report-global-filter-form');if(!form)return;
  const template=<?= json_encode($template) ?>;const filters=<?= json_encode($filters) ?>;
  const insertBefore=form.querySelector('.report-student-field')||form.querySelector('.report-per-page-field');
  const addSelect=function(label,name,options){const row=document.createElement('div');row.className='field-row';const fieldLabel=document.createElement('label');fieldLabel.className='field-label';fieldLabel.textContent=label;const select=document.createElement('select');select.className='field-input field-select';select.name=name;options.forEach(function(option){const item=document.createElement('option');item.value=option.value;item.textContent=option.label;item.selected=String(filters[name]||'')===String(option.value);select.appendChild(item);});row.append(fieldLabel,select);insertBefore.before(row);};
  if(template==='saldo-tabungan'){
    addSelect('Status Siswa','siswa_status',[{value:'active',label:'Aktif'},{value:'archived',label:'Arsip/Lulus'},{value:'all',label:'Semua'}]);
    addSelect('Status Saldo','saldo_status',[{value:'',label:'Semua Saldo'},{value:'ada_saldo',label:'Ada Saldo'},{value:'saldo_nol',label:'Saldo Nol'}]);
  }else{
    addSelect('Tahun Ajaran','tahun_tagihan',[{value:'',label:'Semua Tahun Ajaran'},<?= implode(',',array_map(static fn($year)=>json_encode(['value'=>$year['label'],'label'=>$year['label']]),$years)) ?>]);
    addSelect('Komponen','komponen_tagihan',[{value:'',label:'Semua Komponen'},<?= implode(',',array_map(static fn($key,$label)=>json_encode(['value'=>$key,'label'=>$label]),array_keys($billingCategories),$billingCategories)) ?>]);
    addSelect('Status','status',[{value:'',label:'Semua Status'},{value:'tidak_ditagihkan',label:'Tidak Ditagihkan'},{value:'belum_bayar',label:'Belum Bayar'},{value:'cicilan',label:'Cicilan'},{value:'lunas',label:'Lunas'},{value:'rekonsiliasi',label:'Perlu Rekonsiliasi'},{value:'dibatalkan',label:'Dibatalkan'}]);
    addSelect('Status Siswa','siswa_status',[{value:'active',label:'Aktif'},{value:'archived',label:'Arsip/Lulus'},{value:'all',label:'Semua'}]);
  }
});
</script><?php endif; ?>
<div class="recap-report-header"><div class="recap-report-copy"><span class="recap-class-overline">Laporan Global</span><h1><?= report_e($report['title']) ?></h1><p><?= report_e($report['subtitle']) ?> · <?= number_format($totalRows) ?> baris hasil filter.</p></div>
<form method="get" class="recap-header-controls report-filter-card report-template-filters report-global-filter-form <?= report_e($templateFilterClass) ?>"><input type="hidden" name="template" value="<?= report_e($template) ?>"><span class="recap-filter-label">Filter Laporan</span>
<?php if(in_array($template,['penerimaan','setoran','tabungan-siswa'],true)||$template==='per-item'): $rangeLabel=$template==='per-item'?report_item_date_period_label($filters):report_date_range_label($filters['tanggal_awal'],$filters['tanggal_akhir']); $datePeriodStyle=$template==='per-item'&&($perItemUsesMonthly||$perItemUsesAnnual)?' style="display:none"':''; ?><div class="field-row report-date-range-field" data-per-item-period="date"<?= $datePeriodStyle ?>><label class="field-label">Tanggal Transaksi</label><div class="report-date-range-control report-date-range-picker" data-range-picker data-empty-label="<?= report_e($rangeLabel) ?>"><input type="hidden" name="tanggal_awal" value="<?= report_e($filters['tanggal_awal']) ?>"><input type="hidden" name="tanggal_akhir" value="<?= report_e($filters['tanggal_akhir']) ?>"><button type="button" class="report-date-range-button" aria-expanded="false"><span class="report-date-range-icon">📅</span><span class="report-date-range-value"><?= report_e($rangeLabel) ?></span></button><div class="report-date-range-popover" hidden><label><span>Mulai</span><input type="date" value="<?= report_e($filters['tanggal_awal']) ?>" data-range-start></label><label><span>Sampai</span><input type="date" value="<?= report_e($filters['tanggal_akhir']) ?>" data-range-end></label><div class="report-date-range-popover-actions"><button type="button" class="btn btn-primary btn-sm" data-range-apply>Terapkan</button></div></div></div></div><?php endif; ?>
<?php if(in_array($template,['status','spp-tahunan'],true)||$template==='per-item'): ?><div class="field-row"<?= $template==='per-item'?' data-per-item-period="academic-year"'.($perItemUsesAnnual?'':' style="display:none"'):'' ?>><label class="field-label">Tahun Ajaran</label><select class="field-input field-select" name="tahun_ajaran"><?php foreach($years as $year): ?><option value="<?= report_e($year['label']) ?>" <?= $filters['tahun_ajaran']===$year['label']?'selected':'' ?>><?= report_e($year['label'].' · '.$year['status']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['status','per-item','penerimaan'],true)): ?><div class="field-row"><label class="field-label">Kategori</label><select class="field-input field-select" name="kategori"<?= $template==='per-item'?' data-report-item-category':'' ?>><?php if($template==='penerimaan'): ?><option value="semua">Semua kategori</option><?php endif; ?><?php foreach($categories as $key=>$label): ?><option value="<?= report_e($key) ?>" <?= $filters['kategori']===$key?'selected':'' ?>><?= report_e($label) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if($template==='status'): ?><div class="field-row"><label class="field-label">Bulan Tagihan</label><select class="field-input field-select" name="bulan_awal"><?php foreach(report_months() as $code=>$month): ?><option value="<?= $code ?>" <?= $filters['bulan_awal']===$code?'selected':'' ?>><?= $month ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if($template==='per-item'): $monthPeriodStyle=$perItemUsesMonthly?'':' style="display:none"'; $monthNames=report_months(); $monthStartLabel=$monthNames[$filters['bulan_awal']]??'Bulan'; $monthEndLabel=$monthNames[$filters['bulan_akhir']]??'Bulan'; ?><div class="field-row report-month-range-field" data-per-item-period="month"<?= $monthPeriodStyle ?>><label class="field-label">Periode Tagihan</label><div class="report-month-range-control report-month-range-picker" data-month-range-picker data-empty-label="Pilih bulan tagihan"><input type="hidden" name="bulan_awal" value="<?= report_e($filters['bulan_awal']) ?>"><input type="hidden" name="bulan_akhir" value="<?= report_e($filters['bulan_akhir']) ?>"><button type="button" class="report-month-range-button" aria-expanded="false"><span class="report-month-range-icon" aria-hidden="true">&#128197;</span><span class="report-month-range-value"><?= report_e($monthStartLabel.' sampai '.$monthEndLabel) ?></span></button><div class="report-month-range-popover" hidden><label><span>Mulai</span><select data-month-range-start><?php foreach($monthNames as $code=>$month): ?><option value="<?= $code ?>" <?= $filters['bulan_awal']===$code?'selected':'' ?>><?= report_e($month) ?></option><?php endforeach; ?></select></label><label><span>Sampai</span><select data-month-range-end><?php foreach($monthNames as $code=>$month): ?><option value="<?= $code ?>" <?= $filters['bulan_akhir']===$code?'selected':'' ?>><?= report_e($month) ?></option><?php endforeach; ?></select></label><div class="report-month-range-popover-actions"><button type="button" class="btn btn-primary btn-sm" data-month-range-apply>Terapkan</button></div></div></div></div><div class="field-row report-year-range-field" data-per-item-period="month"<?= $monthPeriodStyle ?>><label class="field-label">Rentang Tahun Tagihan</label><div class="report-year-range-control report-year-range-picker" data-year-range-picker data-empty-label="Pilih tahun tagihan"><input type="hidden" name="tahun_awal" value="<?= (int)$filters['tahun_awal'] ?>"><input type="hidden" name="tahun_akhir" value="<?= (int)$filters['tahun_akhir'] ?>"><button type="button" class="report-year-range-button" aria-expanded="false"><span class="report-year-range-icon" aria-hidden="true">&#128197;</span><span class="report-year-range-value"><?= report_e((int)$filters['tahun_awal'].' sampai '.(int)$filters['tahun_akhir']) ?></span></button><div class="report-year-range-popover" hidden><label><span>Mulai</span><input type="number" min="2000" max="2100" value="<?= (int)$filters['tahun_awal'] ?>" data-year-range-start></label><label><span>Sampai</span><input type="number" min="2000" max="2100" value="<?= (int)$filters['tahun_akhir'] ?>" data-year-range-end></label><div class="report-year-range-popover-actions"><button type="button" class="btn btn-primary btn-sm" data-year-range-apply>Terapkan</button></div></div></div></div><?php endif; ?>
<?php if($template!=='setoran'): ?><div class="field-row"><label class="field-label">Kelas/Rombel</label><select class="field-input field-select" name="kelas"><option value="" <?= $filters['kelas']===''?'selected':'' ?>>Semua Kelas</option><?php foreach($classLevels as $level): ?><option value="tingkat:<?= $level ?>" <?= $filters['kelas']==='tingkat:'.$level?'selected':'' ?>>Semua Kelas <?= $level ?></option><?php endforeach; ?><?php foreach($classes as $class): ?><option value="rombel:<?= (int)$class['id'] ?>" <?= $filters['kelas']==='rombel:'.((int)$class['id'])?'selected':'' ?>><?= report_e(class_label($class)) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['penerimaan','tabungan-siswa','setoran'],true)): ?><div class="field-row"><label class="field-label">Operator</label><select class="field-input field-select" name="operator"><option value=""><?= report_e($operatorFilterLabel) ?></option><?php foreach($operatorOptions as $operator): ?><option value="<?= (int)$operator['id'] ?>" <?= $filters['operator']==(string)$operator['id']?'selected':'' ?>><?= report_e($operator['nama']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if($template==='tabungan-siswa'): ?><div class="field-row"><label class="field-label">Jenis Mutasi</label><select class="field-input field-select" name="mutasi"><option value="" <?= $filters['mutasi']===''?'selected':'' ?>>Semua Mutasi</option><option value="masuk" <?= $filters['mutasi']==='masuk'?'selected':'' ?>>Masuk</option><option value="keluar" <?= $filters['mutasi']==='keluar'?'selected':'' ?>>Keluar</option></select></div><?php endif; ?>
<?php if(in_array($template,['penerimaan','setoran'],true)): ?><div class="field-row"><label class="field-label">Metode</label><select class="field-input field-select" name="metode"><option value="">Semua metode</option><?php foreach(['Tunai','VA','Qris'] as $method): ?><option <?= $filters['metode']===$method?'selected':'' ?>><?= $method ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['status','spp-tahunan','per-item'],true)): ?><div class="field-row"><label class="field-label">Status</label><select class="field-input field-select" name="status"><option value="">Semua status</option><?php foreach(['tidak_ditagihkan'=>'Tidak Ditagihkan','belum_bayar'=>'Belum Bayar','cicilan'=>'Cicilan','lunas'=>'Lunas','rekonsiliasi'=>'Perlu Rekonsiliasi','ada_pembayaran'=>'Ada Pembayaran','tunggakan'=>'Memiliki Tunggakan'] as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['status','spp-tahunan'],true)): ?><div class="field-row"><label class="field-label">Status Siswa</label><select class="field-input field-select" name="siswa_status"><?php foreach(['active'=>'Aktif','archived'=>'Arsip/Lulus','all'=>'Semua'] as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['siswa_status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if($template!=='setoran'): ?><div class="field-row full-span report-student-field"><label class="field-label" for="global-siswa-search">Cari Siswa (Nama / NIS / NIS Diknas)</label><div class="search-box"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input type="text" id="global-siswa-search" data-student-search data-student-list="global-siswa-list" data-student-select-callback="selectReportStudentSearchOption" data-student-query-target="global-student-query" data-student-class-filter="[name=kelas]" value="<?= report_e($studentSearchDisplay) ?>" placeholder="Ketik nama, NIS, atau NIS Diknas..." autocomplete="off"><input type="hidden" id="global-student-query" name="q" value="<?= report_e($filters['q']) ?>"></div><datalist id="global-siswa-list"><?php foreach($studentOptions as $studentOption): $studentLevel=(string)($studentOption['master_tingkat']?:$studentOption['KELAS']); $studentClassLabel=class_label(['tingkat'=>$studentLevel,'kode_rombel'=>$studentOption['kode_rombel']??'BELUM','is_placeholder'=>$studentOption['is_placeholder']??1]); ?><option value="<?= report_e($studentOption['NAMA']) ?>" data-nis="<?= report_e($studentOption['NO_INDUK']) ?>" data-diknas="<?= report_e((string)($studentOption['NO_induk_diknas']??'')) ?>" data-nama="<?= report_e($studentOption['NAMA']) ?>" data-kelas="<?= report_e($studentClassLabel) ?>" data-kelas-id="<?= (int)($studentOption['master_kelas_id']??0) ?>" data-tingkat="<?= report_e($studentLevel) ?>"><?= report_e($studentOption['NAMA']) ?> (<?= report_e($studentClassLabel) ?>)</option><?php endforeach; ?></datalist></div><?php endif; ?><div class="field-row report-per-page-field"><label class="field-label">Baris/Halaman</label><select class="field-input field-select" name="per_page"><?php foreach([25,50,100] as $size): ?><option <?= $filters['per_page']===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select></div><div class="report-filter-actions"><button class="btn btn-primary" type="submit">Tampilkan Rekap</button><a class="btn btn-ghost" href="template.php?template=<?= urlencode($template) ?>">Reset</a></div></form></div>
<?php if(isset($report['error'])): ?><div class="alert alert-error report-template-alert"><?= report_e($report['error']) ?></div><?php endif; ?>
<div class="recap-period-strip report-template-strip"><div class="report-strip-copy"><strong><?= report_e($registry[$template]['label']) ?></strong><span><?= report_e($report['subtitle']) ?></span></div><div class="report-strip-tools"><span class="report-result-pill"><?= report_e($resultRangeLabel) ?></span><div class="report-export-actions" aria-label="Export laporan"><a class="btn btn-ghost report-export-btn" target="_blank" href="export_global.php?<?= http_build_query(array_merge($exportQuery,['format'=>'print'])) ?>">Cetak</a><a class="btn btn-ghost report-export-btn" href="export_global.php?<?= http_build_query(array_merge($exportQuery,['format'=>'pdf'])) ?>">PDF</a><a class="btn btn-primary report-export-btn" href="export_global.php?<?= http_build_query(array_merge($exportQuery,['format'=>'excel'])) ?>">Excel</a></div></div></div>
<div class="report-template-summary"><?php if($summaryCards): ?><div class="report-summary-grid"><?php foreach($summaryCards as $label=>$value): ?><div class="report-summary-card"><span><?= report_e($label) ?></span><strong><?= report_e($value) ?></strong></div><?php endforeach; ?></div><?php endif; ?></div>
<div class="table-container class-recap-scroll report-wide-table report-template-table-wrap"><table class="payment-table class-recap-table report-template-table"><thead><tr><th>No</th><?php foreach($report['columns'] as $column): ?><th><?= report_e($column[1]) ?></th><?php endforeach; ?></tr></thead><tbody><?php if(!$pagination['rows']): ?><tr><td colspan="<?= count($report['columns'])+1 ?>"><div class="empty-state"><p>Tidak ada data</p><span>Ubah filter atau lengkapi data master yang dibutuhkan.</span></div></td></tr><?php else: foreach($pagination['rows'] as $index=>$row): ?><tr><td><?= (($pagination['page']-1)*$pagination['per_page'])+$index+1 ?></td><?php foreach($report['columns'] as $column): $key=$column[0];$type=$column[2]??'text';$value=$row[$key]??''; ?><td><?php if($type==='money'): ?><?= report_money($value) ?><?php elseif($type==='money_optional'): ?><?= $value===null||$value===''?'-':report_money($value) ?><?php elseif($type==='status'): ?><span class="report-status status-<?= report_e(report_status_key((string)$value)) ?>"><?= report_e($value) ?></span><?php elseif($type==='html'&&is_array($value)): ?><span class="matrix-main status-<?= report_e($value['status']??'') ?>"><?= report_e($value['text']??'') ?></span><small><?= report_e($value['sub']??'') ?></small><?php elseif($type==='nis'||$key==='nis'): ?><span class="badge-nis"><?= report_e($value) ?></span><?php if(!empty($row['diknas']??$row['nis_diknas']??$row['NO_induk_diknas']??'')): ?><small class="report-secondary-id">Diknas <?= report_e($row['diknas']??$row['nis_diknas']??$row['NO_induk_diknas']) ?></small><?php endif; ?><?php elseif($type==='kelas'||$key==='kelas'): ?><div class="du-class-year-cell"><span class="kelas-badge"><?= report_e($value) ?></span></div><?php else: ?><?= report_e($value) ?><?php endif; ?></td><?php endforeach; ?></tr><?php endforeach; endif; ?></tbody></table></div>
<?php if($moneyTotals): ?><div class="report-total-section" style="margin-top:16px"><div class="card-title">Total Rupiah</div><div class="report-summary-grid"><?php foreach($moneyTotals as $total): ?><div class="report-summary-card"><span><?= report_e($total['label']) ?></span><strong><?= report_money($total['value']) ?></strong></div><?php endforeach; ?></div></div><?php endif; ?>
<?php render_pagination('template.php', $query, $pagination['page'], $pagination['pages'], $pagination['total'], $pagination['per_page'], 'baris'); ?>
<?php if($template==='setoran'&&!empty($report['details'])): $settlementDetailTotal=array_sum(array_map(fn($detail)=>(float)($detail['nominal']??0),$report['details'])); ?><div class="report-settlement-details"><div class="report-detail-header"><div><span>Detail Setoran</span><h3>Rincian Penerimaan Pembayaran</h3><p><?= number_format(count($report['details'])) ?> transaksi pembayaran yang membentuk rekap ini.</p></div><div class="report-detail-total"><span>Total Detail</span><strong><?= report_money($settlementDetailTotal) ?></strong></div></div><div class="table-container report-detail-table"><table class="payment-table"><thead><tr><th>Waktu</th><th>No. Transaksi</th><th>Siswa</th><th>Komponen</th><th>Metode</th><th>Nominal</th></tr></thead><tbody><?php foreach($detailPagination['rows'] as $detail): ?><tr><td><?= report_e($detail['tanggal']) ?></td><td><?= report_e($detail['nomor']) ?></td><td><?= report_e($detail['nis'].' · '.$detail['nama']) ?></td><td><?= report_e($detail['komponen']) ?></td><td><?= report_e($detail['metode']) ?></td><td><?= report_money($detail['nominal']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php render_pagination('template.php', $query, $detailPagination['page'], $detailPagination['pages'], $detailPagination['total'], $detailPagination['per_page'], 'transaksi', 'detail_page'); ?></div><?php endif; ?></section>
</main></div><script src="../assets/js/app.js?v=7.5"></script><?php if($template==='per-item'): ?><script>
document.addEventListener('DOMContentLoaded',function(){
  const category=document.querySelector('[data-report-item-category]');
  const monthFields=Array.from(document.querySelectorAll('[data-per-item-period="month"]'));
  const dateFields=Array.from(document.querySelectorAll('[data-per-item-period="date"]'));
  const academicYearFields=Array.from(document.querySelectorAll('[data-per-item-period="academic-year"]'));
  const monthlyCategories=new Set(['spp']);
  const annualCategories=new Set(<?= json_encode(array_keys(annual_fee_components())) ?>);
  function syncPerItemPeriodFields(){
    const value=category?.value||'';
    const isMonthly=monthlyCategories.has(value);
    const isAnnual=annualCategories.has(value);
    monthFields.forEach(field=>{field.style.display=isMonthly?'':'none';});
    dateFields.forEach(field=>{field.style.display=(!isMonthly&&!isAnnual)?'':'none';});
    academicYearFields.forEach(field=>{field.style.display=isAnnual?'':'none';});
  }
  category?.addEventListener('change',syncPerItemPeriodFields);
  syncPerItemPeriodFields();
});
</script><?php endif; ?></body></html>
