<?php
require_once '../includes/security.php';
security_bootstrap_session();
require_once '../koneksi.php'; require_once '../includes/auth.php'; require_once '../includes/reports.php'; require_once '../includes/pagination.php';
requireRole(['admin','bendahara','kasir']);
$registry=report_registry(); $template=(string)report_input_scalar($_GET, 'template');
if(!isset($registry[$template])){ header('Location: global.php'); exit; }
$filters=report_filters($koneksi,$_GET);
$classes=report_classes($koneksi);$defaults=report_template_defaults($template,$_GET,$filters,$classes);$filters=$defaults['filters'];$missingRombel=$defaults['missing_rombel'];
try { $report=report_build($koneksi,$template,$filters); }
catch(Throwable $e){ $report=['title'=>$registry[$template]['label'],'subtitle'=>'Gagal memuat laporan','columns'=>[],'rows'=>[],'error'=>security_exception_message($e,'Laporan tidak dapat dimuat.','report-template')]; }
if($missingRombel){$report['rows']=[];$report['error']='Belum ada rombel nyata. Admin perlu membuat Master Kelas/Rombel lalu memindahkan siswa dari placeholder Belum Ditentukan.';}
$pagination=report_paginate($report['rows'],$filters,false); $years=report_years($koneksi); $operators=report_operators($koneksi); $categories=report_categories($koneksi); $query=array_merge($_GET,$filters,['template'=>$template]);
function template_url(array $changes=[]):string { global $query; return 'template.php?'.http_build_query(array_merge($query,$changes)); }
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title><?= report_e($report['title']) ?> | SistemSPP</title><link rel="icon" href="../assets/img/favicon.png"><link rel="stylesheet" href="../assets/css/style.css?v=7.0"><script>(function(){document.documentElement.setAttribute('data-theme',localStorage.getItem('spp_theme')||'dark')})();</script></head><body>
<div class="bg-orbs"><div class="orb orb-1"></div><div class="orb orb-2"></div><div class="orb orb-3"></div></div><div class="layout"><?php include '../includes/sidebar.php'; ?><main class="main-content">
<div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()" aria-label="Buka navigasi"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button><div class="topbar-title"><h2><?= report_e($report['title']) ?></h2><span class="breadcrumb"><a href="global.php">Laporan Global</a> / <?= report_e($registry[$template]['label']) ?></span></div><div class="clock-badge" id="liveClock">--:--:--</div></div>
<section class="main-card"><form method="get" class="report-filter-grid report-template-filters"><input type="hidden" name="template" value="<?= report_e($template) ?>">
<?php if(in_array($template,['penerimaan','setoran','tabungan-siswa'],true)): $rangeLabel=report_date_range_label($filters['tanggal_awal'],$filters['tanggal_akhir']); ?><div class="field-row report-date-range-field"><label class="field-label">Tanggal Transaksi</label><div class="report-date-range-control report-date-range-picker" data-range-picker data-empty-label="<?= report_e($rangeLabel) ?>"><input type="hidden" name="tanggal_awal" value="<?= report_e($filters['tanggal_awal']) ?>"><input type="hidden" name="tanggal_akhir" value="<?= report_e($filters['tanggal_akhir']) ?>"><button type="button" class="report-date-range-button" aria-expanded="false"><span class="report-date-range-icon">📅</span><span class="report-date-range-value"><?= report_e($rangeLabel) ?></span></button><div class="report-date-range-popover" hidden><label><span>Mulai</span><input type="date" value="<?= report_e($filters['tanggal_awal']) ?>" data-range-start></label><label><span>Sampai</span><input type="date" value="<?= report_e($filters['tanggal_akhir']) ?>" data-range-end></label><div class="report-date-range-popover-actions"><button type="button" class="btn btn-primary btn-sm" data-range-apply>Terapkan</button></div></div></div></div><?php endif; ?>
<?php if(in_array($template,['status','spp-tahunan'],true)): ?><div class="field-row"><label class="field-label">Tahun Ajaran</label><select class="field-input field-select" name="tahun_ajaran"><?php foreach($years as $year): ?><option value="<?= report_e($year['label']) ?>" <?= $filters['tahun_ajaran']===$year['label']?'selected':'' ?>><?= report_e($year['label'].' · '.$year['status']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['status','per-item','penerimaan','setoran'],true)): ?><div class="field-row"><label class="field-label">Kategori</label><select class="field-input field-select" name="kategori"><?php if(in_array($template,['penerimaan','setoran'],true)): ?><option value="semua">Semua kategori</option><?php endif; ?><?php foreach($categories as $key=>$label): ?><option value="<?= report_e($key) ?>" <?= $filters['kategori']===$key?'selected':'' ?>><?= report_e($label) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if($template==='status'): ?><div class="field-row"><label class="field-label">Bulan Tagihan</label><select class="field-input field-select" name="bulan_awal"><?php foreach(report_months() as $code=>$month): ?><option value="<?= $code ?>" <?= $filters['bulan_awal']===$code?'selected':'' ?>><?= $month ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['per-item','tabungan-kelas'],true)): ?><div class="field-row"><label class="field-label">Tahun</label><input class="field-input" type="number" min="2000" max="2100" name="tahun" value="<?= $filters['tahun'] ?>"></div><div class="field-row"><label class="field-label">Bulan <?= $template==='per-item'?'Awal':'' ?></label><select class="field-input field-select" name="bulan_awal"><?php foreach(report_months() as $code=>$month): ?><option value="<?= $code ?>" <?= $filters['bulan_awal']===$code?'selected':'' ?>><?= $month ?></option><?php endforeach; ?></select></div><?php if($template==='per-item'): ?><div class="field-row"><label class="field-label">Bulan Akhir</label><select class="field-input field-select" name="bulan_akhir"><?php foreach(report_months() as $code=>$month): ?><option value="<?= $code ?>" <?= $filters['bulan_akhir']===$code?'selected':'' ?>><?= $month ?></option><?php endforeach; ?></select></div><?php endif; ?><?php endif; ?>
<?php if(in_array($template,['tabungan-kelas','tabungan-siswa'],true)): ?><div class="field-row"><label class="field-label">Mode</label><select class="field-input field-select" name="mode"><?php $modes=$template==='tabungan-kelas'?['harian'=>'Harian','bulanan'=>'Bulanan']:['buku'=>'Buku Saldo','transaksi'=>'Daftar Transaksi'];foreach($modes as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['mode']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if($template!=='setoran'): ?><div class="field-row"><label class="field-label">Kelas/Rombel</label><select class="field-input field-select" name="kelas"><option value="0">Semua rombel</option><?php foreach($classes as $class): ?><option value="<?= (int)$class['id'] ?>" <?= $filters['kelas']==(int)$class['id']?'selected':'' ?>><?= report_e(class_label($class)) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['penerimaan','tabungan-siswa','setoran'],true)): ?><div class="field-row"><label class="field-label">Operator</label><select class="field-input field-select" name="operator"><option value="">Semua operator</option><?php foreach($operators as $operator): ?><option value="<?= (int)$operator['id'] ?>" <?= $filters['operator']==(string)$operator['id']?'selected':'' ?>><?= report_e($operator['nama']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['penerimaan','setoran'],true)): ?><div class="field-row"><label class="field-label">Metode</label><select class="field-input field-select" name="metode"><option value="">Semua metode</option><?php foreach(['Tunai','VA','Qris'] as $method): ?><option <?= $filters['metode']===$method?'selected':'' ?>><?= $method ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['status','spp-tahunan','per-item'],true)): ?><div class="field-row"><label class="field-label">Status</label><select class="field-input field-select" name="status"><option value="">Semua status</option><?php foreach(['tidak_ditagihkan'=>'Tidak Ditagihkan','belum_bayar'=>'Belum Bayar','cicilan'=>'Cicilan','lunas'=>'Lunas','rekonsiliasi'=>'Perlu Rekonsiliasi','ada_pembayaran'=>'Ada Pembayaran','tunggakan'=>'Memiliki Tunggakan'] as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($template,['status','spp-tahunan'],true)): ?><div class="field-row"><label class="field-label">Status Siswa</label><select class="field-input field-select" name="siswa_status"><?php foreach(['active'=>'Aktif','archived'=>'Arsip/Lulus','all'=>'Semua'] as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['siswa_status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if($template!=='setoran'): ?><div class="field-row"><label class="field-label">Cari Siswa</label><input class="field-input" name="q" value="<?= report_e($filters['q']) ?>" placeholder="Nama atau NIS"></div><?php endif; ?><div class="field-row"><label class="field-label">Baris/Halaman</label><select class="field-input field-select" name="per_page"><?php foreach([25,50,100] as $size): ?><option <?= $filters['per_page']===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select></div><div class="report-filter-actions"><button class="btn btn-primary" type="submit">Tampilkan</button><a class="btn btn-ghost" href="template.php?template=<?= urlencode($template) ?>">Reset</a></div></form></section>
<?php if(isset($report['error'])): ?><div class="alert alert-error"><?= report_e($report['error']) ?></div><?php endif; ?>
<section class="main-card report-result-card"><div class="card-title-row"><div><div class="card-title"><?= report_e($report['title']) ?></div><p class="payment-auto-note"><?= report_e($report['subtitle']) ?></p></div><div class="report-export-actions"><?php $exportQuery=$query;$exportQuery['page']=1; ?><a class="btn btn-ghost" target="_blank" href="export_global.php?<?= http_build_query(array_merge($exportQuery,['format'=>'print'])) ?>">Cetak</a><a class="btn btn-ghost" href="export_global.php?<?= http_build_query(array_merge($exportQuery,['format'=>'pdf'])) ?>">PDF</a><a class="btn btn-primary" href="export_global.php?<?= http_build_query(array_merge($exportQuery,['format'=>'excel'])) ?>">Excel</a></div></div>
<div class="report-summary-grid"><?php foreach(report_summaries($report['rows']) as $label=>$value): ?><div class="report-summary-card"><span><?= report_e($label) ?></span><strong><?= report_e($value) ?></strong></div><?php endforeach; ?></div>
<div class="table-container report-wide-table"><table class="payment-table"><thead><tr><th>No</th><?php foreach($report['columns'] as $column): ?><th><?= report_e($column[1]) ?></th><?php endforeach; ?></tr></thead><tbody><?php if(!$pagination['rows']): ?><tr><td colspan="<?= count($report['columns'])+1 ?>"><div class="empty-state"><p>Tidak ada data</p><span>Ubah filter atau lengkapi data master yang dibutuhkan.</span></div></td></tr><?php else: foreach($pagination['rows'] as $index=>$row): ?><tr><td><?= (($pagination['page']-1)*$pagination['per_page'])+$index+1 ?></td><?php foreach($report['columns'] as $column): $key=$column[0];$type=$column[2]??'text';$value=$row[$key]??''; ?><td><?php if($type==='money'): ?><?= report_money($value) ?><?php elseif($type==='status'): ?><span class="report-status status-<?= report_e(report_status_key((string)$value)) ?>"><?= report_e($value) ?></span><?php elseif($type==='html'&&is_array($value)): ?><span class="matrix-main status-<?= report_e($value['status']??'') ?>"><?= report_e($value['text']??'') ?></span><small><?= report_e($value['sub']??'') ?></small><?php elseif($type==='nis'||$key==='nis'): ?><span class="badge-nis"><?= report_e($value) ?></span><?php if(!empty($row['diknas']??$row['nis_diknas']??$row['NO_induk_diknas']??'')): ?><small class="report-secondary-id">Diknas <?= report_e($row['diknas']??$row['nis_diknas']??$row['NO_induk_diknas']) ?></small><?php endif; ?><?php elseif($type==='kelas'||$key==='kelas'): ?><div class="du-class-year-cell"><span class="kelas-badge"><?= report_e($value) ?></span></div><?php else: ?><?= report_e($value) ?><?php endif; ?></td><?php endforeach; ?></tr><?php endforeach; endif; ?></tbody></table></div>
<?php render_pagination('template.php', $query, $pagination['page'], $pagination['pages'], $pagination['total'], $pagination['per_page'], 'baris'); ?>
<?php if($template==='setoran'&&!empty($report['details'])): ?><h3 style="margin-top:24px">Rincian Penerimaan Pembayaran</h3><div class="table-container"><table class="payment-table"><thead><tr><th>Waktu</th><th>No. Transaksi</th><th>Siswa</th><th>Komponen</th><th>Metode</th><th>Nominal</th></tr></thead><tbody><?php foreach($report['details'] as $detail): ?><tr><td><?= report_e($detail['tanggal']) ?></td><td><?= report_e($detail['nomor']) ?></td><td><?= report_e($detail['nis'].' · '.$detail['nama']) ?></td><td><?= report_e($detail['komponen']) ?></td><td><?= report_e($detail['metode']) ?></td><td><?= report_money($detail['nominal']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
</main></div><script src="../assets/js/app.js?v=7.0"></script></body></html>
