<?php
session_start();require_once __DIR__.'/../koneksi.php';require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../includes/legacy_activation.php';
requireRole(['admin','kasir']);
if(unit_all_readonly()){http_response_code(409);exit('Pilih SD, SMP, atau SMA di sidebar untuk aktivasi siswa Legacy.');}
if(empty($_SESSION['csrf_legacy_activation']))$_SESSION['csrf_legacy_activation']=bin2hex(random_bytes(32));
$id=(int)($_POST['id']??$_GET['id']??0);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!is_string($_POST['csrf_token']??null)||!hash_equals($_SESSION['csrf_legacy_activation'],$_POST['csrf_token'])){http_response_code(403);exit('Token CSRF tidak valid.');}
    try{if(array_key_exists('pangkal',$_POST))throw new RuntimeException('Formulir aktivasi kedaluwarsa; muat ulang halaman.');if(($_POST['confirmed']??'')!=='1')throw new RuntimeException('Konfirmasikan tahun, kelas, dan tarif operasional.');legacy_activate($koneksi,$id,(int)($_POST['class_id']??0),(int)($_POST['year_id']??0),array_intersect_key($_POST,array_flip(['spp','psb','komite','du'])),(int)$_SESSION['admin_id'],(string)$_SESSION['admin_nama']);header('Location: daftar.php');exit;}catch(Throwable $e){http_response_code(409);$error=$e instanceof mysqli_sql_exception?'Aktivasi dibatalkan; periksa status dan relasi siswa.':$e->getMessage();}
}elseif($_SERVER['REQUEST_METHOD']!=='GET'){http_response_code(405);exit;}
$s=$koneksi->prepare('SELECT s.*,m.source_class,m.source_name,m.raw_data FROM siswa s JOIN legacy_student_import m ON m.student_id=s.id WHERE s.id=?');$s->bind_param('i',$id);$s->execute();$student=$s->get_result()->fetch_assoc();$s->close();if(!$student){http_response_code(404);exit('Siswa Legacy tidak ditemukan pada unit ini.');}
$classes=class_all($koneksi,true,false);$years=$koneksi->query("SELECT id,label,status FROM tahun_ajaran WHERE status IN ('published','draft') ORDER BY label='".du_current_academic_year()."' DESC,status='published' DESC,label DESC")->fetch_all(MYSQLI_ASSOC);
$rates=[];foreach($years as $year)foreach($classes as $class)$rates[$year['id']][$class['id']]=spp_current_effective_rate($koneksi,(string)$class['tingkat'],0,$year['label']);
function la_e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="id" data-palette="<?= unit_palette_for_view() ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aktivasi Legacy | SistemSPP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/css/style.css?v=<?= filemtime(__DIR__.'/../assets/css/style.css') ?>"><link rel="stylesheet" href="../assets/css/backup_restore.css?v=<?= filemtime(__DIR__.'/../assets/css/backup_restore.css') ?>"><script>(function(){document.documentElement.setAttribute('data-theme',localStorage.getItem('spp_theme')||'light');})();</script></head><body><div class="layout">
?><!doctype html><html lang="id" data-palette="<?= unit_palette_for_view() ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aktivasi Legacy | SistemSPP</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/css/date_controls.css?v=<?= filemtime(__DIR__.'/../assets/css/date_controls.css') ?>"><link rel="stylesheet" href="../assets/css/backup_restore.css?v=<?= filemtime(__DIR__.'/../assets/css/backup_restore.css') ?>"><script>(function(){document.documentElement.setAttribute('data-theme',localStorage.getItem('spp_theme')||'light');})();</script></head><body><div class="layout">
<?php include __DIR__.'/../includes/sidebar.php'; ?><main class="main-content dbt-main"><div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()" id="btn-sidebar-toggle" aria-label="Buka menu">☰</button><div class="topbar-title"><h2>Aktifkan &amp; Tempatkan</h2><span class="breadcrumb">Data Siswa / Legacy</span></div><div class="clock-badge" id="liveClock">--:--:--</div></div><div class="db-tools-page"><section class="dbt-card"><h2><?= la_e($student['NAMA']) ?> · <?= la_e($student['NO_INDUK']) ?></h2><p>Kelas sumber: <strong><?= la_e($student['source_class']) ?></strong> · <?= la_e($student['source_name']) ?></p><p>Tarif sumber (informasi, tidak diterapkan): <?php $raw=json_decode($student['raw_data'],true);foreach(['SPP_PERBULAN','POMG','DAFTAR_ULANG'] as $field): ?><?= la_e($field) ?> = <?= la_e($raw[$field]??'tidak tercatat') ?>; <?php endforeach; ?></p><p>Penempatan ini menjadi awal riwayat SistemSPP. Aktivasi tidak menerbitkan tagihan atau membuat rekening Tabungan.</p><?php if($error): ?><div class="dbt-warning" role="alert"><?= la_e($error) ?></div><?php endif; ?>
<?php if($student['legacy_pending']): ?><form method="post" id="legacy-activation"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="csrf_token" value="<?= la_e($_SESSION['csrf_legacy_activation']) ?>"><div class="dbt-import-grid"><div><label for="class-id">Kelas/rombel aktif</label><select name="class_id" id="class-id" required><option value="">Pilih rombel</option><?php foreach($classes as $c): ?><option value="<?= $c['id'] ?>"><?= la_e($c['label']) ?></option><?php endforeach; ?></select></div><div><label for="year-id">Tahun ajaran yang dikonfirmasi</label><select name="year_id" id="year-id" required><?php foreach($years as $y): ?><option value="<?= $y['id'] ?>"><?= la_e($y['label'].' · '.$y['status']) ?></option><?php endforeach; ?></select></div></div><p id="legacy-rate-status" role="status">Pilih rombel untuk melihat tarif master.</p><div class="dbt-import-grid"><?php foreach(['spp'=>'SPP sesuai master','psb'=>'PSB','komite'=>'Komite per bulan','du'=>'Daftar Ulang'] as $key=>$label): ?><div><label for="fee-<?= $key ?>"><?= $label ?> (Rp)</label><input id="fee-<?= $key ?>" name="<?= $key ?>" type="number" min="0" step="0.01" value="0" required <?= $key==='spp'?'readonly':'' ?>></div><?php endforeach; ?></div><label><input type="checkbox" name="confirmed" value="1" required> Saya mengonfirmasi tahun, rombel, dan tarif operasional ini.</label><p><button class="btn btn-primary" type="submit">Aktifkan &amp; Tempatkan</button> <a class="btn btn-ghost" href="daftar.php?status=legacy">Batal</a></p></form><?php else: ?><p>Siswa telah diaktifkan; kiriman ulang tidak membuat penempatan.</p><?php endif; ?></section></div></main></div><script id="legacy-rates" type="application/json"><?= json_encode($rates,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_QUOT|JSON_HEX_APOS) ?></script><script src="../assets/js/date_format.js?v=<?= filemtime(__DIR__ . '/../assets/js/date_format.js') ?>"></script>
  <script src="../assets/js/app.js?v=<?= filemtime(__DIR__ . '/../assets/js/app.js') ?>"></script><script src="../assets/js/legacy_activation.js?v=<?= filemtime(__DIR__.'/../assets/js/legacy_activation.js') ?>"></script></body></html>
