<?php
/** Return routes are generated by the server, never supplied as arbitrary URLs. */
function payment_return_create(int $paymentId, int $unitId, array $query, string $route='riwayat_daftar_ulang.php'): string
{
    if (!in_array($route,['lihat.php','riwayat_daftar_ulang.php'],true)) throw new InvalidArgumentException('Tujuan kembali tidak valid.');
    foreach ($_SESSION['payment_returns'] ?? [] as $key => $entry) {
        if (($entry['expires'] ?? 0) < time()) unset($_SESSION['payment_returns'][$key]);
    }
    $query = array_intersect_key($query, array_flip(['q','student_id','kelas','tahun_ajaran','status','operator','per_page','page','selected','selected_unit','view','search','tanggal','tanggal_awal','tanggal_akhir']));
    while (count($_SESSION['payment_returns'] ?? []) >= 512) array_shift($_SESSION['payment_returns']);
    $token = bin2hex(random_bytes(24));
    $_SESSION['payment_returns'][$token] = ['actor'=>(int)$_SESSION['admin_id'], 'scope'=>unit_active_id(),
        'unit'=>$unitId, 'payment'=>$paymentId, 'expires'=>time()+7200, 'query'=>$query, 'route'=>$route];
    return $token;
}

function payment_return_entry($token, int $paymentId): ?array
{
    if (!is_string($token) || !preg_match('/^[a-f0-9]{48}$/D', $token)) return null;
    $entry = $_SESSION['payment_returns'][$token] ?? null;
    return $entry && $entry['expires'] >= time() && $entry['actor'] === (int)($_SESSION['admin_id'] ?? 0)
        && $entry['scope'] === unit_active_id() && $entry['unit'] === unit_active_id()
        && $entry['payment'] === $paymentId ? $entry : null;
}

function payment_return_url($token, int $paymentId): string
{
    if (!$token) return 'lihat.php';
    $entry = payment_return_entry($token, $paymentId);
    return ($entry['route'] ?? 'riwayat_daftar_ulang.php') . ($entry ? '?'.http_build_query($entry['query']) : '');
}

function payment_return_edit_url($token, int $id): string
{
    if (!$token) return 'edit.php?id='.$id;
    return 'edit.php?' . http_build_query(['id'=>$id, 'return_context'=>is_string($token) ? $token : '']);
}

function payment_edit_draft_save(int $id, $token): void
{
    if (!payment_return_entry($token, $id)) return;
    $draft = $_POST;
    unset($draft['csrf_token'], $draft['aksi'], $draft['id']);
    if (!is_string($draft['activity_request_key'] ?? null) || !preg_match('/^[a-f0-9]{32}$/D', $draft['activity_request_key'])) unset($draft['activity_request_key']);
    $_SESSION['payment_returns'][$token]['draft'] = $draft;
}

/** Restore only submitted form controls, escaping all user text before rendering. */
function payment_edit_restore_markup(string $html, array $draft): string
{
    $excluded=['aksi','id','csrf_token','return_context'];
    $find=static function(string $attrs)use($draft,$excluded){
        if(!preg_match('/\bname="([^"]+)"/',$attrs,$m))return null;
        $name=html_entity_decode($m[1],ENT_QUOTES,'UTF-8');
        return !in_array($name,$excluded,true)&&isset($draft[$name])&&is_scalar($draft[$name])?(string)$draft[$name]:null;
    };
    $html=preg_replace_callback('/<input\b([^>]*)>/i',static function($m)use($find){
        $value=$find($m[1]);if($value===null||preg_match('/\btype="(?:checkbox|radio|file|submit|button)"/i',$m[1]))return $m[0];
        $attrs=preg_replace('/\s+value="[^"]*"/i','',$m[1]);
        return '<input'.$attrs.' value="'.htmlspecialchars($value,ENT_QUOTES,'UTF-8').'">';
    },$html);
    $html=preg_replace_callback('/<textarea\b([^>]*)>.*?<\/textarea>/is',static function($m)use($find){$value=$find($m[1]);return $value===null?$m[0]:'<textarea'.$m[1].'>'.htmlspecialchars($value,ENT_QUOTES,'UTF-8').'</textarea>';},$html);
    return preg_replace_callback('/<select\b([^>]*)>(.*?)<\/select>/is',static function($m)use($find){
        $value=$find($m[1]);if($value===null)return $m[0];
        $body=preg_replace_callback('/<option\b([^>]*)>(.*?)<\/option>/is',static function($o)use($value){
            $attrs=preg_replace('/\s+selected(?:="[^"]*")?/i','',$o[1]);
            $option=preg_match('/\bvalue="([^"]*)"/',$attrs,$v)?html_entity_decode($v[1],ENT_QUOTES,'UTF-8'):strip_tags($o[2]);
            return '<option'.$attrs.($option===$value?' selected':'').'>'.$o[2].'</option>';
        },$m[2]);return '<select'.$m[1].'>'.$body.'</select>';
    },$html)??$html;
}
