<!DOCTYPE html>
<html lang="id" data-palette="<?= unit_palette_for_view() ?>"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Riwayat Daftar Ulang | SistemSPP</title>
<link rel="icon" href="../assets/img/favicon.png?v=2"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<?php foreach(['style','payment_history','payment_details','registration_history','workspace_readability'] as $css): ?><link rel="stylesheet" href="../assets/css/<?= $css ?>.css?v=<?= filemtime(__DIR__.'/../assets/css/'.$css.'.css') ?>"><?php endforeach; ?>
<script>document.documentElement.dataset.theme=localStorage.getItem('spp_theme')||'light';</script>
</head><body class="payment-history-page registration-history-page" data-readable-workspace="registration-history"><div class="layout">
<?php include __DIR__.'/sidebar.php'; ?>
<main class="main-content"><div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()" id="btn-sidebar-toggle" aria-label="Buka navigasi"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><div class="topbar-title"><h2>Riwayat Daftar Ulang</h2><span class="breadcrumb">SistemSPP / Pembayaran / Daftar Ulang</span></div><div class="clock-badge" id="liveClock">--:--:--</div></div>
<div class="ph-page-content">
<?php if($flash): ?><div class="alert alert-<?= authorization_escape($flash['type']??'error') ?>" role="status"><?= authorization_escape($flash['msg']??'') ?></div><?php endif; ?>
<?php if($selectionMissing): ?><div class="alert alert-info" role="status">Kelompok sebelumnya tidak ada pada halaman hasil saat ini. Filter tetap dipertahankan; periksa halaman atau sesuaikan filter.</div><?php endif; ?>
<header class="ph-hero"><div class="ph-hero-copy"><span class="ph-hero-icon"><?= authorization_icon('history') ?></span><div><h1>Riwayat Daftar Ulang</h1><p><?= $deleted?'Arsip pembayaran Daftar Ulang berdasarkan bukti penghapusan.':'Pantau tagihan dan seluruh cicilan siswa per tahun ajaran.' ?></p></div></div><nav class="ph-tabs" aria-label="Jenis riwayat"><?php foreach(['active'=>'Riwayat Aktif','deleted'=>'Riwayat Dihapus'] as $tab=>$label): ?><a href="<?= authorization_escape('riwayat_daftar_ulang.php?'.http_build_query(array_merge($query,['view'=>$tab,'page'=>1,'selected'=>null]))) ?>" <?= $view===$tab?'aria-current="page"':'' ?>><?= $label ?></a><?php endforeach; ?></nav></header>
<section class="ph-filter-card"><form method="get" class="ph-filter-form du-filter-form">
<input type="hidden" name="view" value="<?= $view ?>"><input type="hidden" name="student_id" data-student-identity="1" value="<?= $f['student_id'] ?>">
<?php if($deleted): foreach($f['values']['status'] as $status): ?><input type="hidden" name="status[]" value="<?= authorization_escape($status) ?>"><?php endforeach; endif; ?>
<div class="ph-filter-intro"><?= authorization_icon('filter') ?><div><strong>Filter Riwayat</strong><small>Pilih siswa, kelas, tahun ajaran, dan operator.</small></div></div>
<div class="field-row du-search-field"><label class="field-label" for="du-history-student">Cari Siswa (Nama / NIS / NIS Diknas)</label><div class="search-box"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="m17 17 4 4"/></svg><input id="du-history-student" type="text" data-student-search data-student-fit-viewport data-student-list="du-history-student-list" data-student-select-callback="selectReportStudentSearchOption" data-student-query-target="du-history-student-query" value="<?= authorization_escape($studentDisplay) ?>" placeholder="Ketik nama, NIS, atau NIS Diknas..." autocomplete="off"><input id="du-history-student-query" type="hidden" name="q" value="<?= authorization_escape($f['q']) ?>"></div>
<datalist id="du-history-student-list"><?php foreach($students as $student): ?><option value="<?= authorization_escape($student['NAMA']) ?>" data-student-id="<?= (int)$student['student_id'] ?>" data-unit-id="<?= (int)$student['unit_id'] ?>" data-nis="<?= authorization_escape($student['NO_INDUK']) ?>" data-diknas="<?= authorization_escape($student['NO_induk_diknas']??'') ?>" data-nama="<?= authorization_escape($student['NAMA']) ?>" data-kelas="<?= authorization_escape($student['KELAS']) ?>"><?= authorization_escape($student['NAMA']) ?></option><?php endforeach; ?></datalist></div>
<?php foreach(['kelas'=>'Kelas/Rombel','tahun_ajaran'=>'Tahun Ajaran','status'=>'Status Pelunasan'] as $name=>$label): if($deleted && $name==='status')continue; ?><div class="field-row"><label class="field-label" for="du-filter-<?= $name ?>"><?= $label ?></label><select id="du-filter-<?= $name ?>" name="<?= $name ?>" class="field-input field-select" data-filter-multiple><option value="">Semua <?= $name==='kelas'?'kelas':($name==='tahun_ajaran'?'tahun ajaran':'status') ?></option><?php foreach($f['options'][$name] as $value=>$text): ?><option value="<?= authorization_escape($value) ?>"><?= authorization_escape($text) ?></option><?php endforeach; ?></select></div><?php endforeach; ?>
<?php history_operator_field($f['options']['operator'],'du-history-operator'); ?>
<div class="field-row"><label class="field-label" for="du-per-page">Data per halaman</label><select id="du-per-page" name="per_page" class="field-input field-select"><?php foreach([10,25,50,100] as $size): ?><option value="<?= $size ?>" <?= $size===$f['per_page']?'selected':'' ?>><?= $size ?> / halaman</option><?php endforeach; ?></select></div>
<div class="ph-filter-actions"><button type="submit" class="btn btn-primary">Tampilkan Rekap</button><a class="btn btn-ghost" href="riwayat_daftar_ulang.php?view=<?= $view ?>"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 11a9 9 0 1 1 2 7M3 4v7h7"/></svg> Reset</a><?php if(hasRole(['admin','kasir']) && !unit_all_readonly()): ?><a class="btn btn-primary" href="form.php">+ Input Pembayaran</a><?php endif; ?></div>
<noscript><label class="field-row du-search-field">Cari nama/NIS<input class="field-input" name="q_plain" value="<?= authorization_escape($f['q']) ?>"></label></noscript>
</form></section>
<section class="du-summary <?= $deleted?'is-archive':'' ?>" aria-label="Ringkasan seluruh hasil filter"><?php foreach($deleted?['Siswa / Periode'=>number_format($summary['students']),'Transaksi Dihapus'=>number_format($summary['transactions']),'Daftar Ulang Dihapus'=>payment_history_money($summary['deleted_amount'])]:['Siswa / Periode'=>number_format($summary['students']),'Total Tagihan'=>payment_history_money($summary['bill']),'Sudah Dibayar'=>payment_history_money($summary['paid']),'Sisa Cicilan'=>payment_history_money($summary['remaining'])] as $label=>$value): ?><div><small><?= $label ?></small><strong><?= $value ?></strong></div><?php endforeach; ?></section><?php if(!$deleted && !filter_is_all($f['values']['operator'])): ?><section class="du-operator-summary" aria-label="Pembayaran operator terpilih"><div><small>Pembayaran operator terpilih</small><strong><?= payment_history_money($summary['operator_paid']) ?></strong></div><p>Nominal Daftar Ulang dari operator terpilih. Tagihan, total terbayar, sisa, dan status lunas menghitung seluruh pembayaran siswa/periode yang cocok.</p></section><?php endif; ?><p class="du-summary-caption">Ringkasan seluruh hasil filter · <?= unit_label(unit_active_id()) ?><?= $deleted?' · Nilai dihapus bukan saldo tagihan aktif.':'' ?></p>
<div class="ph-workspace" data-registration-workspace data-view="<?= $view ?>">
<section class="ph-list-panel"><header class="ph-panel-heading"><div><h3><?= authorization_icon('history') ?> Daftar Siswa / Periode</h3><p>Menampilkan <?= $first ?>&ndash;<?= $last ?> dari <?= number_format($summary['students']) ?> siswa/periode.</p></div></header>
<div class="ph-record-list"><?php foreach($rows as $i=>$row): $selected=(int)$row['tagihan_id']===$selectedId && (int)$row['unit_id']===$selectedUnit; $href='riwayat_daftar_ulang.php?'.http_build_query(array_merge($query,['selected'=>$row['tagihan_id'],'selected_unit'=>$row['unit_id']])); ?>
<a class="ph-record du-record <?= $selected?'is-selected':'' ?> <?= $deleted?'is-deleted':'' ?>" href="<?= authorization_escape($href) ?>" data-registration-record data-id="<?= (int)$row['tagihan_id'] ?>" data-unit="<?= (int)$row['unit_id'] ?>" <?= $selected?'aria-current="true"':'' ?>>
<span class="ph-record-number"><?= $offset+$i+1 ?></span><span class="ph-record-icon"><?= authorization_icon('student') ?></span><div class="ph-record-identity"><strong><?= authorization_escape($row['no_induk']) ?></strong><span><?= authorization_escape($row['nama']) ?></span><small>Diknas <?= authorization_escape($row['NO_induk_diknas']?:'Tidak tercatat') ?></small><?= unit_record_badge($row) ?></div><div class="du-record-period"><span class="kelas-badge">Kelas <?= authorization_escape($row['kelas']) ?></span><small><?= authorization_escape($row['th_ajaran']) ?></small></div>
<div class="du-record-amounts"><?php foreach($deleted?['Dihapus'=>$row['deleted_amount']]:['Tagihan'=>$row['total'],'Terbayar'=>$row['paid'],'Sisa'=>$row['remaining']] as $label=>$amount): ?><div><small><?= $label ?></small><strong><?= payment_history_money($amount) ?></strong></div><?php endforeach; ?></div><span class="ph-status <?= $deleted?'is-deleted':'' ?>"><?= $deleted?'Dihapus':((float)$row['remaining']<=.001?'Lunas':'Belum Lunas') ?></span><?= authorization_icon('right') ?></a>
<?php endforeach; ?><?php if(!$rows): ?><div class="ph-empty"><h3>Tidak ada <?= $deleted?'arsip':'tagihan' ?> sesuai filter</h3><p><?= $deleted?'Arsip hanya memuat snapshot dengan rincian dan identitas tagihan Daftar Ulang yang tercatat.':'Ubah pencarian, kelas, tahun ajaran, atau status.' ?></p></div><?php endif; ?></div>
<?php render_pagination('riwayat_daftar_ulang.php',array_diff_key($query,['selected'=>true,'selected_unit'=>true]),$page,$pages,(int)$summary['students'],$f['per_page'],'siswa/periode'); ?></section>
<section class="ph-detail-panel" data-registration-detail-panel><header class="ph-panel-heading"><div><h3><?= authorization_icon('history') ?> Detail Daftar Ulang</h3><p>Rekap tagihan dan transaksi pada periode terpilih.</p></div><div class="ph-detail-nav"><button class="btn btn-ghost btn-sm" type="button" data-registration-prev aria-label="Siswa/periode sebelumnya"><?= authorization_icon('left') ?></button><button class="btn btn-ghost btn-sm" type="button" data-registration-next aria-label="Siswa/periode berikutnya"><?= authorization_icon('right') ?></button><button class="btn btn-ghost btn-sm" type="button" data-registration-close aria-label="Tutup detail"><?= authorization_icon('close') ?></button></div></header><div class="ph-detail-body" data-registration-detail aria-live="polite"><?php if($detail): registration_render_detail($detail,array_merge($query,['selected'=>$selectedId])); else: ?><p class="ph-empty"><?= authorization_escape($detailError??'Pilih siswa/periode untuk melihat detail.') ?></p><?php endif; ?></div></section></div>
</div></main></div>
<dialog id="du-delete-dialog" class="payment-activity-dialog du-delete-dialog" aria-labelledby="du-delete-title"><form method="post" action="proses.php"><span class="du-danger-icon"><?= authorization_icon('delete') ?></span><h3 id="du-delete-title"><?= transaction_authorization_requires_request()?'Ajukan penghapusan transaksi':'Hapus transaksi?' ?></h3><p data-du-delete-copy></p><p>Seluruh komponen dalam transaksi akan dihapus<?= transaction_authorization_requires_request()?' setelah disetujui Super Admin':'' ?>. Jurnal aktivitas tetap tersimpan.</p><input type="hidden" name="aksi" value="hapus"><input type="hidden" name="id"><input type="hidden" name="return_context"><input type="hidden" name="csrf_token" value="<?= authorization_escape($_SESSION['csrf_payment']) ?>"><?php if(transaction_authorization_requires_request()): ?><label class="field-row"><span class="field-label">Alasan penghapusan</span><textarea class="field-input" name="authorization_reason" minlength="5" maxlength="500" rows="4" required></textarea></label><?php endif; ?><div class="authorization-modal-actions"><button type="button" class="btn btn-ghost" data-close-du-delete>Batal</button><button type="submit" class="btn btn-danger"><?= transaction_authorization_requires_request()?'Ajukan Hapus':'Ya, Hapus Transaksi' ?></button></div></form></dialog>
<dialog class="payment-activity-dialog" id="payment-activity-dialog" aria-labelledby="payment-activity-title"><header class="payment-activity-dialog-header"><div><h3 id="payment-activity-title">Riwayat Aktivitas</h3><p data-activity-subtitle></p></div><button type="button" class="btn btn-ghost btn-sm" data-close-activity>Tutup</button></header><div class="payment-activity-content" aria-live="polite"></div></dialog>
<?php foreach(['registration_history','payment_activity','date_format','app'] as $js): ?><script src="../assets/js/<?= $js ?>.js?v=<?= filemtime(__DIR__.'/../assets/js/'.$js.'.js') ?>"></script><?php endforeach; ?>
</body></html>
