<div class="sw-history-layout">
<section class="sw-card sw-history-list"><header class="sw-card-head"><div><?= savings_icon('document') ?><div><h3>Daftar Transaksi</h3><small>Menampilkan <?= $firstShown ?>–<?= $lastShown ?> dari <?= $totalHistoryRows ?> transaksi.</small></div></div><span class="sw-status is-in"><?= $totalHistoryRows ?> transaksi</span></header>
<div class="sw-transactions"><?php if(!$rows): ?><p class="sw-empty">Belum ada transaksi tabungan pada periode ini.</p><?php endif; ?>
<?php foreach($rows as $i=>$r): $selected=$selectedTransaction && $r['id']===$selectedTransaction['id'] && $r['jenis']===$selectedTransaction['jenis'];$link='riwayat.php?'.http_build_query(array_merge($historyPaginationQuery,['page'=>$page,'jenis'=>$r['jenis'],'id'=>$r['id']])); ?>
<article class="sw-transaction <?= $selected?'is-active':'' ?>" data-kind="<?= $r['jenis'] ?>" data-id="<?= (int)$r['id'] ?>">
<a class="sw-transaction-select" href="<?= savings_e($link) ?>" <?= $selected?'aria-current="true"':'' ?>><span class="sw-row-number"><?= $offset+$i+1 ?></span><div class="sw-row-student"><strong class="badge-nis"><?= savings_e($r['NO_INDUK']) ?></strong><strong><?= savings_e($r['NAMA']) ?></strong><small>NIS Diknas <?= savings_e($r['NO_induk_diknas']?:'—') ?></small><span class="sw-class">Kelas <?= savings_e($r['KELAS']) ?><?= unit_all_readonly()?' · '.savings_e(unit_label((int)$r['unit_id'])):'' ?></span></div><div class="sw-row-date"><?= savings_icon('calendar') ?><span><?= savings_e(spp_date_label($r['TANGGAL'])) ?><small><?= savings_e(substr($r['TANGGAL'],11,8)) ?> WIB</small></span></div><div class="sw-row-amount"><span class="sw-status <?= $r['jenis']==='masuk'?'is-in':'is-out' ?>"><?= savings_icon($r['jenis']==='masuk'?'up':'down') ?><?= ucfirst($r['jenis']) ?></span><strong class="<?= $r['jenis']==='masuk'?'sw-accent':'sw-out' ?>"><?= savings_money($r['jenis']==='masuk'?$r['nominal']:$r['keluar']) ?></strong></div><span class="sw-row-arrow"><?= savings_icon('right') ?></span></a>
<div class="sw-row-print"><?php if($r['can_print']): ?><a class="btn btn-ghost btn-sm" href="<?= savings_e($r['receipt_url']) ?>" target="_blank" rel="noopener"><?= savings_icon('print') ?>Cetak Buku Tabungan</a><?php else: ?><span class="sw-locked-print" title="Cetak hanya untuk transaksi milik sendiri"><?= savings_icon('lock') ?>Cetak terkunci</span><?php endif; ?></div></article><?php endforeach; ?></div>
<?php render_pagination('riwayat.php',$historyPaginationQuery,$page,$totalPages,$totalHistoryRows,$perPage,'transaksi'); ?></section>
<section class="sw-card sw-history-detail" id="sw-history-detail" aria-live="polite" tabindex="-1"><?php if($selectedTransaction): ?><?= savings_detail_html($selectedTransaction) ?><?php else: ?><p class="sw-empty"><?= $requestedSelection?'Transaksi tidak ditemukan dalam cakupan unit Anda.':'Pilih transaksi untuk melihat detail.' ?></p><?php endif; ?></section></div>
<?php if($printTransaction): ?><div class="sw-print-overlay" id="sw-print-modal" role="dialog" aria-modal="true" aria-labelledby="sw-print-title"><section class="sw-print-dialog"><span class="sw-head-icon"><?= savings_icon('print') ?></span><h2 id="sw-print-title">Cetak buku tabungan?</h2><p>Transaksi <?= savings_e($printTransaction['reference']) ?> untuk <?= savings_e($printTransaction['NAMA']) ?> sudah tersimpan. Buku lengkap memuat seluruh transaksi dan saldo berjalan terbaru.</p><div><button type="button" class="btn btn-ghost" id="sw-print-later">Tidak, nanti</button><a class="btn btn-primary" href="<?= savings_e($printTransaction['receipt_url']) ?>" target="_blank" rel="noopener" id="sw-print-now">Ya, cetak buku</a></div><noscript><p><a href="<?= savings_e($printTransaction['receipt_url']) ?>">Buka buku tabungan</a></p><style>.sw-print-overlay{position:static;background:none;backdrop-filter:none}.sw-print-dialog{width:100%}</style></noscript></section></div><?php endif; ?>
