<?php
session_start();
require_once __DIR__.'/../koneksi.php';
require_once __DIR__.'/auth.php';
require_once __DIR__.'/savings_workspace.php';
requireRole(['admin','kasir']);
if(empty($_SESSION['csrf_savings']))$_SESSION['csrf_savings']=bin2hex(random_bytes(32));
$savingsRequestKey=bin2hex(random_bytes(16));
$flash=$_SESSION['flash']??null;unset($_SESSION['flash']);
$prefill_nis=is_string($_GET['nis']??'')?trim($_GET['nis']??''):'';
$students=$koneksi->query('SELECT id,NO_INDUK,NO_induk_diknas,NAMA,KELAS FROM siswa WHERE is_active=1 ORDER BY NAMA,id')->fetch_all(MYSQLI_ASSOC);
$withdrawal=$savingsKind==='keluar';$entryLabel=$withdrawal?'Keluar':'Masuk';$entryTitle=$withdrawal?'Input Penarikan Tabungan':'Input Setoran Tabungan';
?>
<!doctype html><html lang="id" data-palette="<?= unit_palette_for_view() ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tabungan <?= $entryLabel ?> | SistemSPP</title><link rel="icon" href="../assets/img/favicon.png"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><script>(function(){document.documentElement.setAttribute('data-theme',localStorage.getItem('spp_theme')||'light');})();</script>
<?php foreach(['style','date_controls','transaction_workflows','savings_workspace'] as $css): ?><link rel="stylesheet" href="../assets/css/<?= $css ?>.css?v=<?= filemtime(__DIR__.'/../assets/css/'.$css.'.css') ?>"><?php endforeach; ?></head><body><div class="layout"><?php include __DIR__.'/sidebar.php'; ?><main class="main-content"><div class="topbar"><button class="sidebar-toggle" onclick="toggleSidebar()" aria-label="Buka menu"><?= savings_icon('menu') ?></button><div class="topbar-title"><h2>Tabungan <?= $entryLabel ?></h2><span class="breadcrumb">SistemSPP / Tabungan / <?= $entryLabel ?></span></div><div class="clock-badge" id="liveClock">--:--:--</div></div>
<?php if($flash): ?><div class="alert alert-<?= $flash['type']==='success'?'success':'error' ?>" id="flash-msg"><?= savings_e($flash['msg']) ?></div><?php endif; ?>
<div class="page-content sw-page"><div class="sw-entry-layout">
<section class="sw-card sw-student-panel"><header class="sw-entry-head"><span class="sw-head-icon"><?= savings_icon('users') ?></span><div><small>PILIH SISWA</small><h1>Cari dan pilih siswa</h1><p>Cari berdasarkan nama, NIS, atau NIS Diknas. Pilih siswa untuk melihat saldo dan melanjutkan transaksi.</p></div></header>
<label class="search-box sw-student-search"><?= savings_icon('search') ?><input id="siswa-search" type="text" data-student-combobox-ready="1" value="<?= savings_e($prefill_nis) ?>" placeholder="Ketik nama, NIS, atau NIS Diknas…" oninput="pilihSiswaDatalist(this)" autocomplete="off" aria-label="Cari siswa"></label>
<datalist id="siswa-list"><?php foreach($students as $student): ?><option value="<?= savings_e($student['NAMA']) ?>" data-student-id="<?= (int)$student['id'] ?>" data-nis="<?= savings_e($student['NO_INDUK']) ?>" data-diknas="<?= savings_e($student['NO_induk_diknas']) ?>" data-nama="<?= savings_e($student['NAMA']) ?>" data-kelas="<?= savings_e($student['KELAS']) ?>"></option><?php endforeach; ?></datalist>
<h3 class="sw-list-label">Daftar hasil pencarian</h3><div class="sw-student-results" id="sw-students"><?php foreach($students as $student): ?><button type="button" class="sw-student-option" data-nis="<?= savings_e($student['NO_INDUK']) ?>" data-search="<?= savings_e(mb_strtolower(implode(' ',[$student['NAMA'],$student['NO_INDUK'],$student['NO_induk_diknas'],$student['KELAS']]),'UTF-8')) ?>"><span class="sw-avatar"><?= savings_e(mb_strtoupper(mb_substr($student['NAMA'],0,2,'UTF-8'),'UTF-8')) ?></span><span><strong><?= savings_e($student['NAMA']) ?></strong><small>NIS <?= savings_e($student['NO_INDUK']) ?> · Diknas <?= savings_e($student['NO_induk_diknas']?:'—') ?></small></span><span class="sw-class">Kelas <?= savings_e($student['KELAS']) ?></span><span class="sw-selected-mark" hidden><?= savings_icon('check') ?></span></button><?php endforeach; ?><p id="sw-no-students" hidden>Tidak ada siswa yang cocok.</p></div>
<section class="sw-selected-student"><div class="sw-selected-heading"><strong><?= savings_icon('user') ?>Ringkasan Siswa Terpilih</strong><button type="button" class="btn btn-ghost btn-sm" id="sw-change-student"><?= savings_icon('reload') ?>Ubah Siswa</button></div><h2 id="sw-selected-name">Pilih siswa dulu</h2><div class="sw-selected-meta"><div><small>No. Induk</small><strong id="sw-selected-nis">—</strong></div><div><small>NIS Diknas</small><strong id="sw-selected-diknas">—</strong></div><div><small>Saldo Tabungan Saat Ini</small><strong class="sw-accent" id="sw-selected-balance">—</strong></div></div></section></section>
<section class="sw-card sw-entry-panel <?= $withdrawal?'is-withdrawal':'' ?>"><header class="sw-entry-head"><span class="sw-head-icon"><?= savings_icon($withdrawal?'down':'document') ?></span><div><small>TABUNGAN <?= strtoupper($entryLabel) ?></small><h1><?= $entryTitle ?></h1><p><?= $withdrawal?'Masukkan nominal penarikan yang diberikan kepada siswa.':'Masukkan nominal setoran yang diterima dari siswa.' ?></p></div><span class="sw-wallet-icon"><?= savings_icon('wallet') ?></span></header>
<p class="sw-info" id="sw-entry-info"><?= savings_icon('info') ?>Pilih siswa terlebih dahulu di panel sebelah kiri.</p>
<form method="POST" action="proses.php" id="form-tabungan" data-unit="<?= unit_active_id() ?>"><input type="hidden" name="aksi" value="<?= $savingsKind ?>"><input type="hidden" name="csrf_token" value="<?= savings_e($_SESSION['csrf_savings']) ?>"><input type="hidden" name="request_key" value="<?= $savingsRequestKey ?>">
<h3 class="sw-section-title"><?= savings_icon('user') ?>Data Siswa</h3><div class="sw-student-fields"><div class="field-row"><label class="field-label" for="disp-nis">No. Induk</label><input class="field-input" id="disp-nis" name="no_induk" readonly placeholder="Otomatis terisi"></div><div class="field-row"><label class="field-label" for="disp-nama">Nama Siswa</label><input class="field-input" id="disp-nama" readonly placeholder="Otomatis terisi"></div><div class="field-row"><label class="field-label" for="disp-kelas">Kelas</label><input class="field-input" id="disp-kelas" readonly placeholder="Otomatis terisi"></div></div>
<h3 class="sw-section-title"><?= savings_icon('wallet') ?>Info Saldo</h3><div class="sw-balance-box"><?= savings_icon('wallet') ?><div><small>Saldo Tabungan Saat Ini</small><strong id="saldo-preview">Pilih siswa dulu</strong><small><?= $withdrawal?'Penarikan tidak boleh melebihi saldo tersedia.':'Saldo akan terisi otomatis setelah siswa dipilih.' ?></small></div><input type="hidden" id="disp-saldo"><input type="hidden" id="raw-saldo" value="0"></div>
<h3 class="sw-section-title"><?= savings_icon('calendar') ?>Rincian <?= $withdrawal?'Penarikan':'Tabungan' ?></h3><div class="sw-amount-fields"><div class="field-row"><label class="field-label" for="tgl-<?= $savingsKind ?>">Tanggal</label><input class="field-input" type="date" id="tgl-<?= $savingsKind ?>" name="tanggal" readonly required value="<?= date('Y-m-d') ?>"></div><div class="field-row"><label class="field-label" for="nominal-<?= $savingsKind ?>">Nominal <?= $entryLabel ?> (Rp)</label><input class="field-input format-rupiah" id="nominal-<?= $savingsKind ?>" name="nominal" type="text" inputmode="numeric" placeholder="0" required></div><div class="field-row sw-full"><label class="field-label" for="ket-<?= $savingsKind ?>">Keterangan (opsional)</label><input class="field-input" id="ket-<?= $savingsKind ?>" name="keterangan" maxlength="255" placeholder="<?= $withdrawal?'Misal: Penarikan tunai.':'Misal: Setoran rutin.' ?>"></div></div>
<footer class="sw-entry-actions"><button type="submit" class="btn btn-primary" id="btn-simpan"><?= savings_icon('save') ?><?= $withdrawal?'Simpan Penarikan':'Simpan Setoran' ?></button><a class="btn btn-ghost" href="riwayat.php"><?= savings_icon('document') ?>Riwayat</a><a class="btn <?= $withdrawal?'btn-primary':'btn-warning' ?>" href="<?= $withdrawal?'masuk':'keluar' ?>.php"><?= savings_icon($withdrawal?'up':'down') ?>Tabungan <?= $withdrawal?'Masuk':'Keluar' ?></a></footer></form></section></div></div></main></div>
<div class="toast" id="toast"><span id="toast-icon"></span><span id="toast-msg"></span></div><?php include __DIR__.'/spp_warning_modal.php'; ?>
<script src="../assets/js/date_format.js?v=<?= filemtime(__DIR__.'/../assets/js/date_format.js') ?>"></script><script src="../assets/js/app.js?v=<?= filemtime(__DIR__.'/../assets/js/app.js') ?>"></script><script src="../assets/js/savings_entry.js?v=<?= filemtime(__DIR__.'/../assets/js/savings_entry.js') ?>"></script><script src="../assets/js/savings_validation.js?v=<?= filemtime(__DIR__.'/../assets/js/savings_validation.js') ?>"></script></body></html>
