-- SistemSPP - Profiling read-only kolom uang legacy sebelum migrasi DECIMAL.
-- Output hanya agregat; tidak menampilkan NIS, nama, atau isi transaksi.
-- Database wajib dipilih eksplisit oleh caller (`mysql --database=<target>`).

SELECT `table_name`, `column_name`, `row_count`, `null_count`, `negative_count`,
       `more_than_two_decimals`, `min_value`, `max_value`
FROM (
  SELECT 'bayar' table_name,'U_PANGKAL' column_name,COUNT(*) row_count,SUM(U_PANGKAL IS NULL) null_count,SUM(COALESCE(U_PANGKAL,0)<0) negative_count,SUM(ABS(COALESCE(U_PANGKAL,0)*100-ROUND(COALESCE(U_PANGKAL,0)*100))>0.000001) more_than_two_decimals,MIN(U_PANGKAL) min_value,MAX(U_PANGKAL) max_value FROM bayar
  UNION ALL SELECT 'bayar','U_BANGUNAN',COUNT(*),SUM(U_BANGUNAN IS NULL),SUM(COALESCE(U_BANGUNAN,0)<0),SUM(ABS(COALESCE(U_BANGUNAN,0)*100-ROUND(COALESCE(U_BANGUNAN,0)*100))>0.000001),MIN(U_BANGUNAN),MAX(U_BANGUNAN) FROM bayar
  UNION ALL SELECT 'bayar','U_SERAGAM',COUNT(*),SUM(U_SERAGAM IS NULL),SUM(COALESCE(U_SERAGAM,0)<0),SUM(ABS(COALESCE(U_SERAGAM,0)*100-ROUND(COALESCE(U_SERAGAM,0)*100))>0.000001),MIN(U_SERAGAM),MAX(U_SERAGAM) FROM bayar
  UNION ALL SELECT 'bayar','U_KEGIATAN',COUNT(*),SUM(U_KEGIATAN IS NULL),SUM(COALESCE(U_KEGIATAN,0)<0),SUM(ABS(COALESCE(U_KEGIATAN,0)*100-ROUND(COALESCE(U_KEGIATAN,0)*100))>0.000001),MIN(U_KEGIATAN),MAX(U_KEGIATAN) FROM bayar
  UNION ALL SELECT 'bayar','U_SPP',COUNT(*),SUM(U_SPP IS NULL),SUM(COALESCE(U_SPP,0)<0),SUM(ABS(COALESCE(U_SPP,0)*100-ROUND(COALESCE(U_SPP,0)*100))>0.000001),MIN(U_SPP),MAX(U_SPP) FROM bayar
  UNION ALL SELECT 'bayar','U_MAKAN',COUNT(*),SUM(U_MAKAN IS NULL),SUM(COALESCE(U_MAKAN,0)<0),SUM(ABS(COALESCE(U_MAKAN,0)*100-ROUND(COALESCE(U_MAKAN,0)*100))>0.000001),MIN(U_MAKAN),MAX(U_MAKAN) FROM bayar
  UNION ALL SELECT 'bayar','U_SORGA',COUNT(*),SUM(U_SORGA IS NULL),SUM(COALESCE(U_SORGA,0)<0),SUM(ABS(COALESCE(U_SORGA,0)*100-ROUND(COALESCE(U_SORGA,0)*100))>0.000001),MIN(U_SORGA),MAX(U_SORGA) FROM bayar
  UNION ALL SELECT 'bayar','U_INFAQ',COUNT(*),SUM(U_INFAQ IS NULL),SUM(COALESCE(U_INFAQ,0)<0),SUM(ABS(COALESCE(U_INFAQ,0)*100-ROUND(COALESCE(U_INFAQ,0)*100))>0.000001),MIN(U_INFAQ),MAX(U_INFAQ) FROM bayar
  UNION ALL SELECT 'bayar','U_LAIN',COUNT(*),SUM(U_LAIN IS NULL),SUM(COALESCE(U_LAIN,0)<0),SUM(ABS(COALESCE(U_LAIN,0)*100-ROUND(COALESCE(U_LAIN,0)*100))>0.000001),MIN(U_LAIN),MAX(U_LAIN) FROM bayar
  UNION ALL SELECT 'bayar','JUMLAH1',COUNT(*),SUM(JUMLAH1 IS NULL),SUM(COALESCE(JUMLAH1,0)<0),SUM(ABS(COALESCE(JUMLAH1,0)*100-ROUND(COALESCE(JUMLAH1,0)*100))>0.000001),MIN(JUMLAH1),MAX(JUMLAH1) FROM bayar
  UNION ALL SELECT 'bayar','JUMLAH2',COUNT(*),SUM(JUMLAH2 IS NULL),SUM(COALESCE(JUMLAH2,0)<0),SUM(ABS(COALESCE(JUMLAH2,0)*100-ROUND(COALESCE(JUMLAH2,0)*100))>0.000001),MIN(JUMLAH2),MAX(JUMLAH2) FROM bayar
  UNION ALL SELECT 'bayar','JUMLAH3',COUNT(*),SUM(JUMLAH3 IS NULL),SUM(COALESCE(JUMLAH3,0)<0),SUM(ABS(COALESCE(JUMLAH3,0)*100-ROUND(COALESCE(JUMLAH3,0)*100))>0.000001),MIN(JUMLAH3),MAX(JUMLAH3) FROM bayar
  UNION ALL SELECT 'bayar','JUMLAH4',COUNT(*),SUM(JUMLAH4 IS NULL),SUM(COALESCE(JUMLAH4,0)<0),SUM(ABS(COALESCE(JUMLAH4,0)*100-ROUND(COALESCE(JUMLAH4,0)*100))>0.000001),MIN(JUMLAH4),MAX(JUMLAH4) FROM bayar
  UNION ALL SELECT 'bayar','potong_spp',COUNT(*),SUM(potong_spp IS NULL),SUM(COALESCE(potong_spp,0)<0),SUM(ABS(COALESCE(potong_spp,0)*100-ROUND(COALESCE(potong_spp,0)*100))>0.000001),MIN(potong_spp),MAX(potong_spp) FROM bayar
  UNION ALL SELECT 'bayar','total_jumlah',COUNT(*),SUM(total_jumlah IS NULL),SUM(COALESCE(total_jumlah,0)<0),SUM(ABS(COALESCE(total_jumlah,0)*100-ROUND(COALESCE(total_jumlah,0)*100))>0.000001),MIN(total_jumlah),MAX(total_jumlah) FROM bayar
  UNION ALL SELECT 'tabungan','SALDO',COUNT(*),SUM(SALDO IS NULL),SUM(COALESCE(SALDO,0)<0),SUM(ABS(COALESCE(SALDO,0)*100-ROUND(COALESCE(SALDO,0)*100))>0.000001),MIN(SALDO),MAX(SALDO) FROM tabungan
  UNION ALL SELECT 'transaksi_m','MASUK',COUNT(*),SUM(MASUK IS NULL),SUM(COALESCE(MASUK,0)<0),SUM(ABS(COALESCE(MASUK,0)*100-ROUND(COALESCE(MASUK,0)*100))>0.000001),MIN(MASUK),MAX(MASUK) FROM transaksi_m
  UNION ALL SELECT 'transaksi_m','KELUAR',COUNT(*),SUM(KELUAR IS NULL),SUM(COALESCE(KELUAR,0)<0),SUM(ABS(COALESCE(KELUAR,0)*100-ROUND(COALESCE(KELUAR,0)*100))>0.000001),MIN(KELUAR),MAX(KELUAR) FROM transaksi_m
  UNION ALL SELECT 'transaksi_k','MASUK',COUNT(*),SUM(MASUK IS NULL),SUM(COALESCE(MASUK,0)<0),SUM(ABS(COALESCE(MASUK,0)*100-ROUND(COALESCE(MASUK,0)*100))>0.000001),MIN(MASUK),MAX(MASUK) FROM transaksi_k
  UNION ALL SELECT 'transaksi_k','KELUAR',COUNT(*),SUM(KELUAR IS NULL),SUM(COALESCE(KELUAR,0)<0),SUM(ABS(COALESCE(KELUAR,0)*100-ROUND(COALESCE(KELUAR,0)*100))>0.000001),MIN(KELUAR),MAX(KELUAR) FROM transaksi_k
) money_profile
ORDER BY `table_name`, `column_name`;
