-- Dinonaktifkan: aplikasi tidak lagi menerbitkan akun kasir dengan password
-- default bersama. Buat setiap akun melalui Role Management agar password
-- disimpan dengan password_hash() dan dapat diaudit per petugas.
